/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ACTUATOR_MESSAGE_PB_H_INCLUDED
#define PB_ACTUATOR_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ChannelMode {
    ChannelMode_MODE_BINARY = 0,
    ChannelMode_MODE_PWM = 1,
    ChannelMode_MODE_FOLLOW = 2
} ChannelMode;

typedef enum _Comparison {
    Comparison_LESS_THAN = 0,
    Comparison_GREATER_THAN = 1
} Comparison;

typedef enum _SafeMode {
    SafeMode_SAFE_OFF = 0,
    SafeMode_SAFE_ON = 1,
    SafeMode_SAFE_KEEP = 2
} SafeMode;

typedef enum _ChannelStateValue {
    ChannelStateValue_STATE_OFF = 0,
    ChannelStateValue_STATE_ON = 1,
    ChannelStateValue_STATE_PWM = 2
} ChannelStateValue;

typedef enum _StateReason {
    StateReason_REASON_SENSOR_BELOW_THRESHOLD = 0,
    StateReason_REASON_SENSOR_ABOVE_THRESHOLD = 1,
    StateReason_REASON_PWM_CALCULATED = 2,
    StateReason_REASON_HYSTERESIS_ACTIVE = 3,
    StateReason_REASON_STALE_SENSOR_DATA = 4,
    StateReason_REASON_TIMEOUT = 5,
    StateReason_REASON_DISABLED = 6,
    StateReason_REASON_SAFE_MODE = 7
} StateReason;

/* Struct definitions */
typedef struct _ChannelConfig {
    uint32_t number;
    bool enabled;
    ChannelMode mode;
    /* REMOVED: string sensor_input = 4;  // ESP32 doesn't need sensor names - server already knows which sensors to aggregate */
    SafeMode safe_mode;
    /* Binary mode fields */
    float threshold;
    Comparison comparison;
    uint32_t hysteresis_seconds;
    /* PWM mode fields */
    float min_sensor_value;
    float max_sensor_value;
    uint32_t min_pwm;
    uint32_t max_pwm;
    float hysteresis_value; /* Value-based hysteresis (creates deadband) */
    bool invert_logic; /* Invert ON/OFF logic (useful for cooling: turn ON when above threshold, OFF when below) */
} ChannelConfig;

typedef struct _ActuatorConfig {
    char device_id[32];
    uint32_t timestamp;
    pb_size_t channels_count;
    ChannelConfig channels[4];
    uint32_t data_timeout_seconds; /* Timeout for safe mode (default 10s) */
} ActuatorConfig;

typedef struct _ChannelData {
    uint32_t channel; /* Which channel (1-4) */
    float value; /* Aggregated sensor value from server */
    bool fresh; /* true = data is current, false = stale/missing */
} ChannelData;

typedef struct _SensorData {
    uint32_t timestamp;
    pb_size_t channel_data_count;
    ChannelData channel_data[4]; /* One entry per channel */
} SensorData;

typedef struct _ChannelState {
    uint32_t number;
    ChannelStateValue state;
    uint32_t pwm_value; /* Only for PWM/Follow mode */
    StateReason reason;
    float sensor_value; /* Current sensor value used */
    float threshold; /* Threshold used (binary mode) */
} ChannelState;

typedef struct _ActuatorState {
    char device_id[32];
    uint32_t timestamp;
    pb_size_t channels_count;
    ChannelState channels[4];
} ActuatorState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ChannelMode_MIN ChannelMode_MODE_BINARY
#define _ChannelMode_MAX ChannelMode_MODE_FOLLOW
#define _ChannelMode_ARRAYSIZE ((ChannelMode)(ChannelMode_MODE_FOLLOW+1))

#define _Comparison_MIN Comparison_LESS_THAN
#define _Comparison_MAX Comparison_GREATER_THAN
#define _Comparison_ARRAYSIZE ((Comparison)(Comparison_GREATER_THAN+1))

#define _SafeMode_MIN SafeMode_SAFE_OFF
#define _SafeMode_MAX SafeMode_SAFE_KEEP
#define _SafeMode_ARRAYSIZE ((SafeMode)(SafeMode_SAFE_KEEP+1))

#define _ChannelStateValue_MIN ChannelStateValue_STATE_OFF
#define _ChannelStateValue_MAX ChannelStateValue_STATE_PWM
#define _ChannelStateValue_ARRAYSIZE ((ChannelStateValue)(ChannelStateValue_STATE_PWM+1))

#define _StateReason_MIN StateReason_REASON_SENSOR_BELOW_THRESHOLD
#define _StateReason_MAX StateReason_REASON_SAFE_MODE
#define _StateReason_ARRAYSIZE ((StateReason)(StateReason_REASON_SAFE_MODE+1))


#define ChannelConfig_mode_ENUMTYPE ChannelMode
#define ChannelConfig_safe_mode_ENUMTYPE SafeMode
#define ChannelConfig_comparison_ENUMTYPE Comparison




#define ChannelState_state_ENUMTYPE ChannelStateValue
#define ChannelState_reason_ENUMTYPE StateReason


/* Initializer values for message structs */
#define ActuatorConfig_init_default              {"", 0, 0, {ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default, ChannelConfig_init_default}, 0}
#define ChannelConfig_init_default               {0, 0, _ChannelMode_MIN, _SafeMode_MIN, 0, _Comparison_MIN, 0, 0, 0, 0, 0, 0, 0}
#define SensorData_init_default                  {0, 0, {ChannelData_init_default, ChannelData_init_default, ChannelData_init_default, ChannelData_init_default}}
#define ChannelData_init_default                 {0, 0, 0}
#define ActuatorState_init_default               {"", 0, 0, {ChannelState_init_default, ChannelState_init_default, ChannelState_init_default, ChannelState_init_default}}
#define ChannelState_init_default                {0, _ChannelStateValue_MIN, 0, _StateReason_MIN, 0, 0}
#define ActuatorConfig_init_zero                 {"", 0, 0, {ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero, ChannelConfig_init_zero}, 0}
#define ChannelConfig_init_zero                  {0, 0, _ChannelMode_MIN, _SafeMode_MIN, 0, _Comparison_MIN, 0, 0, 0, 0, 0, 0, 0}
#define SensorData_init_zero                     {0, 0, {ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero}}
#define ChannelData_init_zero                    {0, 0, 0}
#define ActuatorState_init_zero                  {"", 0, 0, {ChannelState_init_zero, ChannelState_init_zero, ChannelState_init_zero, ChannelState_init_zero}}
#define ChannelState_init_zero                   {0, _ChannelStateValue_MIN, 0, _StateReason_MIN, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ChannelConfig_number_tag                 1
#define ChannelConfig_enabled_tag                2
#define ChannelConfig_mode_tag                   3
#define ChannelConfig_safe_mode_tag              5
#define ChannelConfig_threshold_tag              6
#define ChannelConfig_comparison_tag             7
#define ChannelConfig_hysteresis_seconds_tag     8
#define ChannelConfig_min_sensor_value_tag       9
#define ChannelConfig_max_sensor_value_tag       10
#define ChannelConfig_min_pwm_tag                11
#define ChannelConfig_max_pwm_tag                12
#define ChannelConfig_hysteresis_value_tag       13
#define ChannelConfig_invert_logic_tag           14
#define ActuatorConfig_device_id_tag             1
#define ActuatorConfig_timestamp_tag             2
#define ActuatorConfig_channels_tag              3
#define ActuatorConfig_data_timeout_seconds_tag  4
#define ChannelData_channel_tag                  1
#define ChannelData_value_tag                    2
#define ChannelData_fresh_tag                    3
#define SensorData_timestamp_tag                 1
#define SensorData_channel_data_tag              2
#define ChannelState_number_tag                  1
#define ChannelState_state_tag                   2
#define ChannelState_pwm_value_tag               3
#define ChannelState_reason_tag                  4
#define ChannelState_sensor_value_tag            5
#define ChannelState_threshold_tag               6
#define ActuatorState_device_id_tag              1
#define ActuatorState_timestamp_tag              2
#define ActuatorState_channels_tag               3

/* Struct field encoding specification for nanopb */
#define ActuatorConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         2) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,          3) \
X(a, STATIC,   SINGULAR, UINT32,   data_timeout_seconds,   4)
#define ActuatorConfig_CALLBACK NULL
#define ActuatorConfig_DEFAULT NULL
#define ActuatorConfig_channels_MSGTYPE ChannelConfig

#define ChannelConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   number,            1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   SINGULAR, UENUM,    safe_mode,         5) \
X(a, STATIC,   SINGULAR, FLOAT,    threshold,         6) \
X(a, STATIC,   SINGULAR, UENUM,    comparison,        7) \
X(a, STATIC,   SINGULAR, UINT32,   hysteresis_seconds,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    min_sensor_value,   9) \
X(a, STATIC,   SINGULAR, FLOAT,    max_sensor_value,  10) \
X(a, STATIC,   SINGULAR, UINT32,   min_pwm,          11) \
X(a, STATIC,   SINGULAR, UINT32,   max_pwm,          12) \
X(a, STATIC,   SINGULAR, FLOAT,    hysteresis_value,  13) \
X(a, STATIC,   SINGULAR, BOOL,     invert_logic,     14)
#define ChannelConfig_CALLBACK NULL
#define ChannelConfig_DEFAULT NULL

#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  channel_data,      2)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL
#define SensorData_channel_data_MSGTYPE ChannelData

#define ChannelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, BOOL,     fresh,             3)
#define ChannelData_CALLBACK NULL
#define ChannelData_DEFAULT NULL

#define ActuatorState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         2) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,          3)
#define ActuatorState_CALLBACK NULL
#define ActuatorState_DEFAULT NULL
#define ActuatorState_channels_MSGTYPE ChannelState

#define ChannelState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   number,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   pwm_value,         3) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    sensor_value,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    threshold,         6)
#define ChannelState_CALLBACK NULL
#define ChannelState_DEFAULT NULL

extern const pb_msgdesc_t ActuatorConfig_msg;
extern const pb_msgdesc_t ChannelConfig_msg;
extern const pb_msgdesc_t SensorData_msg;
extern const pb_msgdesc_t ChannelData_msg;
extern const pb_msgdesc_t ActuatorState_msg;
extern const pb_msgdesc_t ChannelState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ActuatorConfig_fields &ActuatorConfig_msg
#define ChannelConfig_fields &ChannelConfig_msg
#define SensorData_fields &SensorData_msg
#define ChannelData_fields &ChannelData_msg
#define ActuatorState_fields &ActuatorState_msg
#define ChannelState_fields &ChannelState_msg

/* Maximum encoded size of messages (where known) */
#define ACTUATOR_MESSAGE_PB_H_MAX_SIZE           ActuatorConfig_size
#define ActuatorConfig_size                      269
#define ActuatorState_size                       151
#define ChannelConfig_size                       54
#define ChannelData_size                         13
#define ChannelState_size                        26
#define SensorData_size                          66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
