/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "actuator_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ActuatorConfig, ActuatorConfig, 2)


PB_BIND(ChannelConfig, ChannelConfig, AUTO)


PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(ChannelData, ChannelData, AUTO)


PB_BIND(ActuatorState, ActuatorState, AUTO)


PB_BIND(ChannelState, ChannelState, AUTO)













