[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/backend",
    "crates/frontend",
    "crates/firmware-builder",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.85"

[workspace.dependencies]
pnex-core = { path = "crates/core" }
pnex-firmware-builder = { path = "crates/firmware-builder" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[profile.release]
lto = "thin"
strip = true
