//! Instrumentation symbols — original PneX drawings (ISA 5.1 style bubbles
//! and primary elements).

use super::Symbol;

pub const SYMBOLS: &[Symbol] = &[
    Symbol {
        id: "instruments-field-ti",
        category: "instruments",
        name: "Temperature indicator TI (field)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">TI</text>"#,
    },
    Symbol {
        id: "instruments-field-pt",
        category: "instruments",
        name: "Pressure transmitter PT (field)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">PT</text>"#,
    },
    Symbol {
        id: "instruments-field-ft",
        category: "instruments",
        name: "Flow transmitter FT (field)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">FT</text>"#,
    },
    Symbol {
        id: "instruments-field-lt",
        category: "instruments",
        name: "Level transmitter LT (field)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">LT</text>"#,
    },
    Symbol {
        id: "instruments-field-at",
        category: "instruments",
        name: "Analyzer transmitter AT (field)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">AT</text>"#,
    },
    Symbol {
        id: "instruments-panel-tic",
        category: "instruments",
        name: "Temperature controller TIC (main panel)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><path d="M2 40H78" fill="none"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">TIC</text>"#,
    },
    Symbol {
        id: "instruments-panel-pic",
        category: "instruments",
        name: "Pressure controller PIC (main panel)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><path d="M2 40H78" fill="none"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">PIC</text>"#,
    },
    Symbol {
        id: "instruments-aux-panel-fic",
        category: "instruments",
        name: "Flow controller FIC (auxiliary panel)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><path d="M2 37H78M2 43H78" fill="none"/><text x="40" y="23" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">FIC</text>"#,
    },
    Symbol {
        id: "instruments-behind-panel-lic",
        category: "instruments",
        name: "Level controller LIC (behind panel)",
        w: 80,
        h: 80,
        body: r#"<circle cx="40" cy="40" r="38"/><path d="M2 40H78" fill="none" stroke-dasharray="4 3"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">LIC</text>"#,
    },
    Symbol {
        id: "instruments-dcs-field-fi",
        category: "instruments",
        name: "DCS flow indicator FI (field)",
        w: 80,
        h: 80,
        body: r#"<rect x="1" y="1" width="78" height="78"/><circle cx="40" cy="40" r="38" fill="none"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">FI</text>"#,
    },
    Symbol {
        id: "instruments-dcs-console-fic",
        category: "instruments",
        name: "DCS flow controller FIC",
        w: 80,
        h: 80,
        body: r#"<rect x="1" y="1" width="78" height="78"/><circle cx="40" cy="40" r="38" fill="none"/><path d="M2 40H78" fill="none"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">FIC</text>"#,
    },
    Symbol {
        id: "instruments-dcs-console-lic",
        category: "instruments",
        name: "DCS level controller LIC",
        w: 80,
        h: 80,
        body: r#"<rect x="1" y="1" width="78" height="78"/><circle cx="40" cy="40" r="38" fill="none"/><path d="M2 40H78" fill="none"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">LIC</text>"#,
    },
    Symbol {
        id: "instruments-plc-console-pic",
        category: "instruments",
        name: "PLC pressure controller PIC",
        w: 80,
        h: 80,
        body: r#"<rect x="1" y="1" width="78" height="78"/><polygon points="40,1 79,40 40,79 1,40" fill="none"/><path d="M2 40H78" fill="none"/><text x="40" y="27" text-anchor="middle" dominant-baseline="central" font-size="14" fill="currentColor" stroke="none" font-family="sans-serif">PIC</text>"#,
    },
    Symbol {
        id: "instruments-plc-field-fy",
        category: "instruments",
        name: "PLC relay FY (field)",
        w: 80,
        h: 80,
        body: r#"<rect x="1" y="1" width="78" height="78"/><polygon points="40,1 79,40 40,79 1,40" fill="none"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="18" fill="currentColor" stroke="none" font-family="sans-serif">FY</text>"#,
    },
    Symbol {
        id: "instruments-computer-tic",
        category: "instruments",
        name: "Computer temperature controller TIC",
        w: 80,
        h: 80,
        body: r#"<polygon points="21,6 59,6 79,40 59,74 21,74 1,40"/><path d="M2 40H78" fill="none"/><text x="40" y="25" text-anchor="middle" dominant-baseline="central" font-size="17" fill="currentColor" stroke="none" font-family="sans-serif">TIC</text>"#,
    },
    Symbol {
        id: "instruments-interlock",
        category: "instruments",
        name: "Interlock logic",
        w: 80,
        h: 80,
        body: r#"<polygon points="40,1 79,40 40,79 1,40"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="24" fill="currentColor" stroke="none" font-family="sans-serif">I</text>"#,
    },
    Symbol {
        id: "instruments-sensor-stem-tt",
        category: "instruments",
        name: "Temperature sensor on stem TT",
        w: 80,
        h: 120,
        body: r#"<path d="M40 78V119" fill="none"/><circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">TT</text>"#,
    },
    Symbol {
        id: "instruments-sensor-stem-pt",
        category: "instruments",
        name: "Pressure sensor on stem PT",
        w: 80,
        h: 120,
        body: r#"<path d="M40 78V119" fill="none"/><circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">PT</text>"#,
    },
    Symbol {
        id: "instruments-thermowell",
        category: "instruments",
        name: "Temperature element in well",
        w: 100,
        h: 70,
        body: r#"<path d="M1 35H99" fill="none"/><path d="M44 14V50A6 6 0 0 0 56 50V14Z"/><rect x="36" y="2" width="28" height="12" rx="2"/>"#,
    },
    Symbol {
        id: "instruments-pressure-gauge",
        category: "instruments",
        name: "Pressure gauge",
        w: 80,
        h: 120,
        body: r#"<path d="M40 78V119" fill="none"/><circle cx="40" cy="40" r="38"/><path d="M16 58L21 53M13 40H20M16 22L21 27M40 9V16M64 22L59 27M67 40H60M64 58L59 53" fill="none"/><path d="M40 40L58 20" fill="none" stroke-width="3"/><circle cx="40" cy="40" r="4" fill="currentColor"/>"#,
    },
    Symbol {
        id: "instruments-flow-meter",
        category: "instruments",
        name: "Flow meter (generic)",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H28M72 30H99" fill="none"/><circle cx="50" cy="30" r="22"/><polygon points="40,20 64,30 40,40" fill="currentColor"/>"#,
    },
    Symbol {
        id: "instruments-orifice-plate",
        category: "instruments",
        name: "Orifice plate",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H99" fill="none"/><path d="M42 6V54M58 6V54" fill="none"/><path d="M50 4V22M50 38V56" fill="none" stroke-width="3"/>"#,
    },
    Symbol {
        id: "instruments-venturi",
        category: "instruments",
        name: "Venturi tube",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H14M86 30H99" fill="none"/><path d="M14 10H28L44 22H56L72 10H86V50H72L56 38H44L28 50H14Z"/>"#,
    },
    Symbol {
        id: "instruments-magnetic-flowmeter",
        category: "instruments",
        name: "Magnetic flowmeter",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H28M72 30H99" fill="none"/><rect x="28" y="8" width="44" height="44" rx="3"/><text x="50" y="30" text-anchor="middle" dominant-baseline="central" font-size="24" fill="currentColor" stroke="none" font-family="sans-serif">M</text>"#,
    },
    Symbol {
        id: "instruments-vortex-flowmeter",
        category: "instruments",
        name: "Vortex flowmeter",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H28M72 30H99" fill="none"/><rect x="28" y="8" width="44" height="44" rx="3"/><polygon points="34,22 42,30 34,38" fill="currentColor"/><path d="M46 24Q52 16 58 24T66 24M46 36Q52 44 58 36T66 36" fill="none"/>"#,
    },
    Symbol {
        id: "instruments-turbine-flowmeter",
        category: "instruments",
        name: "Turbine flowmeter",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H28M72 30H99" fill="none"/><rect x="28" y="8" width="44" height="44" rx="3"/><path d="M50 30L50 14M50 30L64 38M50 30L36 38" fill="none"/><circle cx="50" cy="30" r="3" fill="currentColor"/>"#,
    },
    Symbol {
        id: "instruments-coriolis-flowmeter",
        category: "instruments",
        name: "Coriolis flowmeter",
        w: 100,
        h: 60,
        body: r#"<path d="M1 30H24M76 30H99" fill="none"/><path d="M24 30C24 4 76 4 76 30" fill="none"/><path d="M24 30C24 56 76 56 76 30" fill="none"/><circle cx="50" cy="30" r="10"/><text x="50" y="30" text-anchor="middle" dominant-baseline="central" font-size="12" fill="currentColor" stroke="none" font-family="sans-serif">C</text>"#,
    },
    Symbol {
        id: "instruments-rotameter",
        category: "instruments",
        name: "Rotameter (variable area)",
        w: 60,
        h: 120,
        body: r#"<path d="M30 1V10M30 110V119" fill="none"/><polygon points="16,10 44,10 36,110 24,110"/><path d="M22 30H26M22 50H26M22 70H26" fill="none"/><polygon points="24,56 36,56 30,68" fill="currentColor"/>"#,
    },
    Symbol {
        id: "instruments-level-gauge-glass",
        category: "instruments",
        name: "Level gauge glass",
        w: 60,
        h: 120,
        body: r#"<path d="M1 18H22M1 102H22" fill="none"/><rect x="22" y="8" width="18" height="104" rx="3"/><rect x="26" y="58" width="10" height="50" fill="currentColor" stroke="none"/><path d="M22 58H40" fill="none"/>"#,
    },
    Symbol {
        id: "instruments-analyzer-element",
        category: "instruments",
        name: "Analyzer probe",
        w: 80,
        h: 120,
        body: r#"<path d="M40 78V119" fill="none"/><circle cx="40" cy="40" r="38"/><text x="40" y="40" text-anchor="middle" dominant-baseline="central" font-size="22" fill="currentColor" stroke="none" font-family="sans-serif">AE</text>"#,
    },
];
