//! Validation compile-only des fonctions du registre — sous-commande
//! `pnex-flow-runtime --check-function <request.json>`.
//!
//! Le backend écrit la requête dans un fichier temp, spawn ce binaire et lit
//! **une ligne JSON** `FunctionValidateResponse` (même contrat qu'une ligne
//! pour `--test-function`). Aucune exécution du code utilisateur :
//! - Starlark : `pnex_node_starlark::executor::check` (directives, syntaxe
//!   avec position, présence de `handle`) ;
//! - JS : compile le code brut dans une VM fraîche via `new AsyncFunction`
//!   (mêmes sémantiques que le wrap runtime — sloppy + `await` légal), sans
//!   l'exécuter. Le constructeur préfixe le corps de ~2 lignes synthétiques :
//!   une sonde `"\n@"` (erreur forcée à la ligne 2 du texte passé) mesure
//!   l'offset du moteur à chaque check — auto-calibrant, robuste aux
//!   versions. Message/stack extraits par `Ctx::catch` en repli Rust.

use std::process::ExitCode;
use std::time::{Duration, Instant};

use pnex_core::{
    FunctionDiagnostic, FunctionLanguage, FunctionValidateRequest, FunctionValidateResponse,
};

/// Point d'entrée du mode `--check-function` : lit la requête, compile (sans
/// exécuter) et imprime **une ligne JSON** `FunctionValidateResponse`. Exit 0
/// même avec diagnostics (`ok:false` EST le résultat) ; exit 1 requête
/// illisible.
pub async fn run(request_path: &str) -> ExitCode {
    let raw = match std::fs::read_to_string(request_path) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("check-function : requête illisible : {e}");
            return ExitCode::FAILURE;
        }
    };
    let req: FunctionValidateRequest = match serde_json::from_str(&raw) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("check-function : requête invalide : {e}");
            return ExitCode::FAILURE;
        }
    };

    let diagnostics = match req.language {
        FunctionLanguage::Starlark => pnex_node_starlark::executor::check(&req.code),
        FunctionLanguage::Js => check_js(&req.code).await,
    };
    let response = FunctionValidateResponse {
        ok: diagnostics.is_empty(),
        diagnostics,
    };
    println!("{}", serde_json::to_string(&response).unwrap_or_default());
    ExitCode::SUCCESS
}

/// Validation JS : VM fraîche (mêmes limites que `exec_js`), prologue
/// `__pnex_check` compilant le code via `new AsyncFunction` sans l'exécuter.
async fn check_js(code: &str) -> Vec<FunctionDiagnostic> {
    use rquickjs::{AsyncContext, AsyncRuntime, Function};

    const PROLOGUE: &str = r#"globalThis.__pnex_check = function (src) {
  const AF = Object.getPrototypeOf(async function () {}).constructor;
  function failure(e) {
    return {
      message: (e && e.message) ? e.message : String(e),
      stack: (e && e.stack) ? String(e.stack) : "",
    };
  }
  // Self-calibration probe: force a syntax error at line 2 of the source we
  // pass — reported_line - 2 = synthetic header offset of this engine build.
  let probe_line = 0;
  try {
    new AF("\n@");
  } catch (e) {
    const m = /:(\d+)/.exec((e && e.stack) ? String(e.stack) : "");
    probe_line = m ? Number(m[1]) : 0;
  }
  try {
    new AF(src);
    return null;
  } catch (e) {
    return JSON.stringify(Object.assign(failure(e), { probe_line: probe_line }));
  }
};
"#;

    let deadline = Instant::now() + Duration::from_secs(2);
    let rt = match AsyncRuntime::new() {
        Ok(rt) => rt,
        Err(e) => return vec![js_infra_diag(e)],
    };
    rt.set_memory_limit(128 * 1024 * 1024).await;
    rt.set_max_stack_size(1024 * 1024).await;
    rt.set_interrupt_handler(Some(Box::new(move || Instant::now() >= deadline)))
        .await;
    let ctx = match AsyncContext::full(&rt).await {
        Ok(ctx) => ctx,
        Err(e) => return vec![js_infra_diag(e)],
    };

    let code = code.to_string();
    let result: Result<Option<String>, rquickjs::Error> = rquickjs::async_with!(ctx => |ctx| {
        let attempt: Result<Option<String>, rquickjs::Error> = (|| {
            ctx.eval::<(), _>(PROLOGUE.as_bytes())?;
            let check: Function = ctx.globals().get("__pnex_check")?;
            Ok(check.call((code.as_str(),))?)
        })();
        match attempt {
            Ok(maybe_json) => Ok(maybe_json),
            Err(e) => {
                // Fallback: surface the thrown JS exception (message +
                // stack) instead of "Exception generated by QuickJS".
                let caught = ctx.catch();
                let obj = caught.into_object();
                let message = obj
                    .as_ref()
                    .and_then(|o| o.get::<_, Option<String>>("message").ok())
                    .flatten();
                let stack = obj
                    .as_ref()
                    .and_then(|o| o.get::<_, Option<String>>("stack").ok())
                    .flatten();
                Ok(Some(serde_json::json!({
                    "message": message.unwrap_or_else(|| e.to_string()),
                    "stack": stack.unwrap_or_default(),
                    "probe_line": 0,
                })
                .to_string()))
            }
        }
    })
    .await;

    let json_text = match result {
        Ok(Some(t)) => t,
        Ok(None) => return Vec::new(),
        Err(e) => return vec![js_infra_diag(e)],
    };
    finalize_js_diag(&json_text)
}

/// Post-traitement du JSON `__pnex_check` : message verbatim + position
/// recalée de l'offset moteur mesuré par la sonde (`probe_line`).
fn finalize_js_diag(json_text: &str) -> Vec<FunctionDiagnostic> {
    let parsed: serde_json::Value = serde_json::from_str(json_text)
        .unwrap_or_else(|_| serde_json::json!({ "message": json_text, "stack": "" }));
    let message = parsed
        .get("message")
        .and_then(|m| m.as_str())
        .unwrap_or("syntax error")
        .to_string();
    let (line, col) = extract_pos(parsed.get("stack").and_then(|s| s.as_str()).unwrap_or(""));
    let probe_line = parsed
        .get("probe_line")
        .and_then(|p| p.as_u64())
        .unwrap_or(0) as u32;
    // Calage : le constructeur reporte la ligne réelle + offset (sonde =
    // erreur forcée à la ligne 2 → offset = probe_line - 2). Sondé à 0
    // (extraction ratée) → position conservée telle quelle (best-effort).
    let line = match (line, probe_line) {
        (Some(l), p) if p > 2 => Some(l.saturating_sub(p - 2).max(1)),
        (other, _) => other,
    };
    vec![FunctionDiagnostic { line, col, message }]
}

/// Diagnostic d'infrastructure (VM impossible / deadline) — traité comme une
/// erreur de script verbatim, ligne inconnue.
fn js_infra_diag(e: impl std::fmt::Display) -> FunctionDiagnostic {
    FunctionDiagnostic {
        line: None,
        col: None,
        message: format!("exécution JS : {e}"),
    }
}

/// Extraction best-effort de la première position `fichier:line` ou
/// `fichier:line:col` d'une stack QuickJS, sans dépendance regex.
/// Ligne/colonne 1-based ; (None, None) si absent.
fn extract_pos(text: &str) -> (Option<u32>, Option<u32>) {
    let bytes = text.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b':' && i + 1 < bytes.len() && bytes[i + 1].is_ascii_digit() {
            let mut j = i + 1;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            let line: u32 = text[i + 1..j].parse().unwrap_or(0);
            if line > 0 {
                let mut col = None;
                if j < bytes.len()
                    && bytes[j] == b':'
                    && j + 1 < bytes.len()
                    && bytes[j + 1].is_ascii_digit()
                {
                    let c0 = j + 1;
                    let mut c1 = c0;
                    while c1 < bytes.len() && bytes[c1].is_ascii_digit() {
                        c1 += 1;
                    }
                    let c: u32 = text[c0..c1].parse().unwrap_or(0);
                    if c > 0 {
                        col = Some(c);
                    }
                }
                return (Some(line), col);
            }
            i = j;
        } else {
            i += 1;
        }
    }
    (None, None)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Starlark delegation smoke test — full coverage lives in
    /// `pnex-node-starlark::executor::tests`.
    #[tokio::test]
    async fn starlark_delegation_ok() {
        assert!(
            pnex_node_starlark::executor::check("def handle(inputs, msg):\n    return inputs")
                .is_empty()
        );
    }

    #[tokio::test]
    async fn js_ok() {
        assert!(
            check_js("function handle(inputs, msg) { return { out: 1 }; }")
                .await
                .is_empty()
        );
    }

    #[tokio::test]
    async fn js_syntax_error() {
        let diags = check_js("function handle(inputs, msg) { return { out: ; }").await;
        assert_eq!(diags.len(), 1);
        assert!(!diags[0].message.is_empty(), "message verbatim attendu");
    }

    #[tokio::test]
    async fn js_syntax_error_line_calibrated() {
        // Error on real line 3 of the source — the self-calibration probe
        // must strip the synthetic AsyncFunction header offset.
        let src = "let a = 1;\nlet b = 2;\nlet c = ;\n";
        let diags = check_js(src).await;
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].line, Some(3), "{:?}", diags[0]);
    }

    #[tokio::test]
    async fn js_top_level_await_legal() {
        // Same semantics as the runtime wrap (async function body): a bare
        // `await` compiles fine and must NOT be flagged.
        assert!(check_js("await 1").await.is_empty());
        // Sloppy mode: undeclared assignment is a compile pass (runtime concern).
        assert!(check_js("x = 1").await.is_empty());
    }

    #[test]
    fn extract_pos_first_match() {
        assert_eq!(extract_pos("at <anonymous> (eval.js:3)"), (Some(3), None));
        assert_eq!(extract_pos("at f (eval:2:7)"), (Some(2), Some(7)));
        assert_eq!(extract_pos("no position here"), (None, None));
        assert_eq!(extract_pos(":0:0"), (None, None));
    }
}
