//! Device PKI (D153, lot L3 of security-tiers.md §6 bis): one certificate
//! authority per org, and the registry of the device certificates it issued.
//! The CA private key lives in the secrets vault (platform secret), never in
//! these tables; a device private key lives only in its firmware image.

use sea_orm_migration::prelude::*;
use sea_orm_migration::sea_orm::DatabaseBackend;

const POSTGRES_UP: &str = r#"
CREATE TABLE org_device_cas (
    org_id bigint NOT NULL,
    cert_pem text NOT NULL,
    key_secret_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT org_device_cas_pkey PRIMARY KEY (org_id),
    CONSTRAINT "fk-org_device_cas-org_id" FOREIGN KEY (org_id)
        REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE TABLE device_certificates (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_id bigint NOT NULL,
    device_registry_id bigint NOT NULL,
    serial character varying(64) NOT NULL,
    fingerprint_sha256 character varying(64) NOT NULL,
    not_after timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT device_certificates_pkey PRIMARY KEY (id),
    CONSTRAINT "fk-device_certificates-org_id" FOREIGN KEY (org_id)
        REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT "fk-device_certificates-device_registry_id" FOREIGN KEY (device_registry_id)
        REFERENCES device_registries(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uniq_device_certificates_fingerprint ON device_certificates USING btree (fingerprint_sha256);
CREATE INDEX idx_device_certificates_device ON device_certificates USING btree (device_registry_id);
"#;

const SQLITE_UP: &str = r#"
CREATE TABLE "org_device_cas" ( "org_id" integer NOT NULL PRIMARY KEY, "cert_pem" text NOT NULL, "key_secret_id" uuid_text NOT NULL, "created_at" timestamp_with_timezone_text NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE );
CREATE TABLE "device_certificates" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "org_id" integer NOT NULL, "device_registry_id" integer NOT NULL, "serial" varchar(64) NOT NULL, "fingerprint_sha256" varchar(64) NOT NULL, "not_after" timestamp_with_timezone_text NOT NULL, "revoked_at" timestamp_with_timezone_text NULL, "created_at" timestamp_with_timezone_text NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE, FOREIGN KEY ("device_registry_id") REFERENCES "device_registries" ("id") ON DELETE CASCADE );
CREATE UNIQUE INDEX uniq_device_certificates_fingerprint ON device_certificates (fingerprint_sha256);
CREATE INDEX idx_device_certificates_device ON device_certificates (device_registry_id);
"#;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
        let script = match m.get_database_backend() {
            DatabaseBackend::Postgres => POSTGRES_UP,
            DatabaseBackend::Sqlite => SQLITE_UP,
            other => {
                return Err(DbErr::Migration(format!(
                    "unsupported database backend: {other:?}"
                )))
            }
        };
        m.get_connection().execute_unprepared(script).await?;
        Ok(())
    }

    async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
        m.get_connection()
            .execute_unprepared(
                "DROP TABLE IF EXISTS device_certificates; DROP TABLE IF EXISTS org_device_cas;",
            )
            .await?;
        Ok(())
    }
}
