//
// Noise link of the device (D156): `Noise_NNpsk0_25519_ChaChaPoly_SHA256`,
// initiator side, keyed by the device's 32-byte pre-shared key
// (ENCRYPTION_KEY). Mirror of the server (pnex_core::frame, Rust `snow`):
//
//   device → server   first message  (-> psk, e)          48 bytes
//   server → device   second message (<- e, ee)           48 bytes
//   then transport messages both ways: ChaCha20-Poly1305, nonce = counter,
//   16-byte tag; a payload above NOISE_MAX_CHUNK is sealed as consecutive
//   chunks in one frame.
//
// The prologue "PNEX-NOISE-1|" + device id binds the link to the device.
// This layer is NOT redundant with TLS (D155): the pre-shared key keeps the
// traffic confidential against a future quantum computer, which ECDHE does
// not. Do not remove it as "double encryption".
//
// Portable C++ (no Arduino): compiled as-is on every chip and by the host
// test (firmware/core-cpp-tests), which replays golden vectors generated by
// the Rust side (crates/pnex-core/tests/noise_goldens.rs).
//
#ifndef PNEX_NOISE_H
#define PNEX_NOISE_H

#include <cstddef>
#include <cstdint>

namespace pnex_noise {

constexpr size_t KEY_LEN = 32;
constexpr size_t TAG_LEN = 16;
constexpr size_t MSG1_LEN = 32 + TAG_LEN;
constexpr size_t MSG2_LEN = 32 + TAG_LEN;
constexpr size_t MAX_MSG = 65535;
constexpr size_t MAX_CHUNK = MAX_MSG - TAG_LEN;

/// One direction of the transport (key + counter nonce).
struct CipherState {
    uint8_t k[KEY_LEN];
    uint64_t n;
};

/// Initiator handshake + transport state of one connection.
class Link {
public:
    /// Starts a handshake with the ephemeral private key `e_priv` (32
    /// random bytes; fixed only in tests). Writes the first message (48
    /// bytes) into `msg1`. `device_id` is the decoded device id.
    void start(const uint8_t psk[KEY_LEN], const char* device_id,
               const uint8_t e_priv[KEY_LEN], uint8_t msg1[MSG1_LEN]);

    /// Reads the server's second message; true = link established.
    bool finish(const uint8_t* msg2, size_t len);

    bool ready() const { return ready_; }

    /// Forgets every key (connection closed).
    void reset();

    /// Sealed size of a `len`-byte payload.
    static size_t sealed_len(size_t len);

    /// Seals `len` bytes into `out`, which must hold sealed_len(len) bytes;
    /// returns that size. `out == in` is allowed (in-place, the camera
    /// path): chunks are moved from the last one down, so no unread input is
    /// overwritten. Any other overlap is unsupported.
    size_t seal(const uint8_t* in, size_t len, uint8_t* out);

    /// Opens a single-message frame of the server (len <= MAX_MSG) into
    /// `out` (len - TAG_LEN bytes, `out == in` allowed); returns the
    /// plaintext length, or SIZE_MAX when forged, replayed or out of order
    /// (the counter only moves on success). The server never sends a
    /// device frame larger than one Noise message.
    size_t open(const uint8_t* in, size_t len, uint8_t* out);

private:
    uint8_t h_[32];
    uint8_t ck_[32];
    uint8_t k_[KEY_LEN];
    uint64_t n_ = 0;
    uint8_t e_priv_[KEY_LEN];
    CipherState tx_;
    CipherState rx_;
    bool ready_ = false;

    void mix_hash(const uint8_t* data, size_t len);
    void mix_key(const uint8_t* ikm, size_t len);
};

/// Transport primitive (exposed for the tests): RFC 8439 AEAD with the Noise
/// nonce (4 zero bytes ‖ counter little-endian) and empty associated data
/// unless `ad` is given.
void aead_seal(const uint8_t k[KEY_LEN], uint64_t n, const uint8_t* ad, size_t ad_len,
               const uint8_t* in, size_t len, uint8_t* out);
bool aead_open(const uint8_t k[KEY_LEN], uint64_t n, const uint8_t* ad, size_t ad_len,
               const uint8_t* in, size_t len, uint8_t* out);

}  // namespace pnex_noise

#endif  // PNEX_NOISE_H
