[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; Serial monitor filters
monitor_filters =
    time
    esp8266_exception_decoder

; Build flags
build_flags =
    -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -D HOST=\"${sysenv.HOST}\"
    -D TOKEN=\"${sysenv.TOKEN}\"
    -D DEVICE_ID=\"${sysenv.DEVICE_ID}\"
    -D WS_SSL=\"${sysenv.WS_SSL}\"
    -D CORE_DEBUG_LEVEL=3
    -D PB_FIELD_16BIT=1
    -D PB_ENABLE_MALLOC=1

; Library directories
lib_extra_dirs = ../common_libs

; Library dependencies
lib_deps =
    densaugeo/base64@^1.4.0
    gilmaimon/ArduinoWebsockets@^0.5.4
    olikraus/U8g2@^2.36.12
    nanopb/Nanopb@^0.4.91
