//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the shape of `_entities/controls.rs` — regenerable by
//! `cargo loco db entities` without a material diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub user_id: i64,
    pub title: String,
    /// One-turn-at-a-time lease (D145); NULL or past = free.
    pub busy_until: Option<DateTimeWithTimeZone>,
    pub last_message_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ai_messages::Entity")]
    AiMessages,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::ai_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessages.def()
    }
}
