//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the shape of `_entities/controls.rs` — regenerable by
//! `cargo loco db entities` without a material diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub conversation_id: Uuid,
    pub seq: i32,
    /// `user` | `assistant` | `tool`.
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    /// Bounded tool trace of an assistant turn (names, arguments, outcome).
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tool_trace: Option<Json>,
    pub page: Option<String>,
    pub tokens_in: Option<i32>,
    pub tokens_out: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversations::Entity",
        from = "Column::ConversationId",
        to = "super::ai_conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AiConversations,
}

impl Related<super::ai_conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversations.def()
    }
}
