//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Annotations sur médias (D55–D60) — versions append-only du document de
//! couche (école `tour_versions`) : `doc` JSONB
//! (`pnex_core::AnnotationDoc`), unique (layer_id, version_number).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "annotation_layer_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uniq_annotation_layer_versions_layer_number")]
    pub layer_id: Uuid,
    #[sea_orm(unique_key = "uniq_annotation_layer_versions_layer_number")]
    pub version_number: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub doc: Json,
    pub author: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::annotation_layers::Entity",
        from = "Column::LayerId",
        to = "super::annotation_layers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AnnotationLayers,
}

impl Related<super::annotation_layers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnnotationLayers.def()
    }
}
