//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "annotations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub site_diagram_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub x: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub y: Decimal,
    pub title: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub fields: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub linked_devices: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub zoom: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub pan_x: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub pan_y: Option<Decimal>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::site_diagrams::Entity",
        from = "Column::SiteDiagramId",
        to = "super::site_diagrams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SiteDiagrams,
}

impl Related<super::site_diagrams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteDiagrams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
