//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Media annotations (D55–D60): identity of a layer. Circular FK
//! `published_version_id`, same pattern as `tours.published_version_id`.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "annotation_layers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub published_version_id: Option<Uuid>,
    /// Pivot UX : le média associé de l'ensemble (NULL légal).
    pub media_asset_id: Option<Uuid>,
    /// Ensemble rattaché à un tour — XOR media_asset_id à la
    /// création ; NULL si le tour est supprimé.
    pub tour_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::annotation_layer_versions::Entity",
        from = "Column::PublishedVersionId",
        to = "super::annotation_layer_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AnnotationLayerVersions,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::annotation_layer_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnnotationLayerVersions.def()
    }
}
