//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Transcription profile (media-ingest.md D164): which registry models
/// a stream uses for VAD, ASR and diarization.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "asr_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    pub asr_model_id: Uuid,
    pub vad_model_id: Option<Uuid>,
    pub diarization_model_id: Option<Uuid>,
    pub diarization_embedding_model_id: Option<Uuid>,
    pub language: String,
    pub beam: i32,
    pub word_timestamps: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::ml_models::Entity",
        from = "Column::AsrModelId",
        to = "super::ml_models::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AsrModel,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
