//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "build_records")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_id: Option<String>,
    pub build_phase: String,
    pub firmware_bin_s3_key: Option<String>,
    pub org_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub fw_version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ota_sha256: Option<String>,
    pub ota_size_bytes: Option<i64>,
    /// Fingerprint of the embedded firmware tree at build time (staleness
    /// tripwire).
    pub sources_fingerprint: Option<String>,
    /// Custom firmware revision compiled by this build (NULL = generic
    /// build).
    pub firmware_revision_id: Option<i64>,
    /// Why a failed build failed (O4): machine code from
    /// `pnex_core::builds::BUILD_FAILURE_CODES`.
    pub failure_code: Option<String>,
    /// Tail of the tool output of a failed build, credentials masked.
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
