//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dashboard_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uniq_dashboard_versions_doc_number")]
    pub dashboard_id: Uuid,
    #[sea_orm(unique_key = "uniq_dashboard_versions_doc_number")]
    pub version_number: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub layout: Json,
    pub author: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dashboards::Entity",
        from = "Column::DashboardId",
        to = "super::dashboards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dashboards,
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboards.def()
    }
}
