//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_registries")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_device_registries_org_device_id")]
    pub device_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub active: bool,
    pub allow_dynamic_measurements: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub discovered_measurements: Option<Json>,
    pub max_unique_measurements: i32,
    #[sea_orm(unique_key = "uniq_device_registries_org_device_id")]
    pub org_id: i64,
    pub predefined_device_id: i64,
    /// SoC observed at admission (Tier 2 custom, no overlay).
    #[sea_orm(nullable)]
    pub soc: Option<String>,
    /// Board variant frozen at registration.
    #[sea_orm(nullable)]
    pub board_id: Option<i64>,
    /// Per-device peripherals state (`{"screen": true}`).
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub peripherals: Option<Json>,
    /// Firmware version announced by the device ("who runs where",
    /// edge-model.md §9) — stamped `PNEX_FW_VERSION` = build record id.
    #[sea_orm(column_type = "Text", nullable)]
    pub fw_version: Option<String>,
    /// OTA admission attested by the announce caps manifest (cap id `ota`).
    pub ota_ready: Option<bool>,
    /// Last announce caps manifest (`CapDesc[]`, incl. custom `metric` /
    /// `command` caps).
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub announced_caps: Option<Json>,
    /// Custom firmware project attached to the device (NULL = generic
    /// preset).
    pub firmware_project_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mcu_boards::Entity",
        from = "Column::BoardId",
        to = "super::mcu_boards::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    McuBoards,
    #[sea_orm(has_many = "super::device_capability_instances::Entity")]
    DeviceCapabilityInstances,
    #[sea_orm(has_one = "super::device_states::Entity")]
    DeviceStates,
    #[sea_orm(has_one = "super::device_tokens::Entity")]
    DeviceTokens,
    #[sea_orm(has_many = "super::flows::Entity")]
    Flows,
    #[sea_orm(has_many = "super::formula_data_sources::Entity")]
    FormulaDataSources,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::predefined_devices::Entity",
        from = "Column::PredefinedDeviceId",
        to = "super::predefined_devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PredefinedDevices,
    #[sea_orm(has_many = "super::regulator_configs::Entity")]
    RegulatorConfigs,
}

impl Related<super::mcu_boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::McuBoards.def()
    }
}

impl Related<super::device_capability_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceCapabilityInstances.def()
    }
}

impl Related<super::device_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceStates.def()
    }
}

impl Related<super::device_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceTokens.def()
    }
}

impl Related<super::flows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flows.def()
    }
}

impl Related<super::formula_data_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormulaDataSources.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDevices.def()
    }
}

impl Related<super::regulator_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegulatorConfigs.def()
    }
}
