//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "device_registries")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_device_registries_org_device_id")]
    pub device_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub active: bool,
    pub allow_dynamic_measurements: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub discovered_measurements: Option<Json>,
    pub max_unique_measurements: i32,
    #[sea_orm(unique_key = "uniq_device_registries_org_device_id")]
    pub org_id: i64,
    pub predefined_device_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::device_tokens::Entity")]
    DeviceTokens,
    #[sea_orm(has_many = "super::formula_data_sources::Entity")]
    FormulaDataSources,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::predefined_devices::Entity",
        from = "Column::PredefinedDeviceId",
        to = "super::predefined_devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PredefinedDevices,
}

impl Related<super::device_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceTokens.def()
    }
}

impl Related<super::formula_data_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormulaDataSources.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
