//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Écrite à la main (D43) : placement carte d'un device —
//! plusieurs devices par POI, mais un device = **un seul** placement à la
//! fois (`device_registry_id` UNIQUE, école `device_positions`). La
//! `location_detail` porte la localisation fine **par device** (in-site),
//! le POI gardant la sienne (bâtiment). Détachement possible (amendement
//! D43, 2026-09-13 : DELETE placement) — l'UNIQUE garantit toujours
//! « au plus un POI à la fois ».

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_placements")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub org_id: i64,
    #[sea_orm(unique)]
    pub device_registry_id: i64,
    /// Slug dénormalisé (école device_positions) pour l'API et la recherche.
    pub device_id: String,
    pub pin_id: Uuid,
    // Localisation fine dans le site (« Rack 3 — Allée B »).
    pub location_detail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_registries::Entity",
        from = "Column::DeviceRegistryId",
        to = "super::device_registries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::map_pins::Entity",
        from = "Column::PinId",
        to = "super::map_pins::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MapPins,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::map_pins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MapPins.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
