//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Écrite à la main (D38) : dernière position GPS connue
//! par device — upsert au tap d'ingestion télémétrie (source `telemetry`)
//! ou via l'endpoint manuel (source `manual`). L'historique complet reste
//! dans OpenObserve (séries `latitude`/`longitude`).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_positions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub org_id: i64,
    #[sea_orm(unique)]
    pub device_registry_id: i64,
    pub device_id: String,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub latitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))")]
    pub longitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((8, 2)))", nullable)]
    pub altitude_m: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((8, 2)))", nullable)]
    pub accuracy_m: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))", nullable)]
    pub speed_mps: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 1)))", nullable)]
    pub heading_deg: Option<Decimal>,
    pub source: String,
    pub positioned_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_registries::Entity",
        from = "Column::DeviceRegistryId",
        to = "super::device_registries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
