//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Camera capture settings, one row per camera device (camera-video.md D76).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_cameras")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_registry_id: i64,
    pub org_id: i64,
    pub framesize: String,
    pub quality: i16,
    pub fps: i16,
    pub capture_mode: String,
    pub vflip: bool,
    pub hmirror: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_registries::Entity",
        from = "Column::DeviceRegistryId",
        to = "super::device_registries::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
