//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::CapabilityMode;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "device_capabilities")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub mode: CapabilityMode,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::predefined_device_capabilities::Entity")]
    PredefinedDeviceCapabilities,
}

impl Related<super::predefined_device_capabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDeviceCapabilities.def()
    }
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        super::predefined_device_capabilities::Relation::PredefinedDevices.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::predefined_device_capabilities::Relation::DeviceCapabilities
                .def()
                .rev(),
        )
    }
}
