//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::FluidGroupType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "fluid_property_groups")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub display_name: String,
    pub group_type: FluidGroupType,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub property_codes: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub default_fluid: Option<String>,
    pub cache_ttl: i32,
    pub is_predefined: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::formulas::Entity")]
    Formulas,
}

impl Related<super::formulas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Formulas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
