//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::FluidCategory;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fluid_catalogs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_fluid_catalogs_org_coolprop")]
    pub org_id: Option<i64>,
    pub name: String,
    #[sea_orm(unique)]
    pub coolprop_name: String,
    pub category: FluidCategory,
    pub is_predefined: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub chemical_formula: Option<String>,
    pub cas_number: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub min_temperature_k: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub max_temperature_k: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub min_pressure_pa: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub max_pressure_pa: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
