//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ConstantKind;
use super::sea_orm_active_enums::DataSourceKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "formula_data_sources")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub device_registry_id: Option<i64>,
    pub unit_conversion_id: Option<i64>,
    pub source_type: DataSourceKind,
    pub measurement_name: Option<String>,
    pub constant_type: Option<ConstantKind>,
    #[sea_orm(column_type = "Text", nullable)]
    pub constant_value: Option<String>,
    #[sea_orm(unique_key = "uniq_formula_data_sources_formula_var")]
    pub variable_name: String,
    pub sort_order: i32,
    #[sea_orm(unique_key = "uniq_formula_data_sources_formula_var")]
    pub formula_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_registries::Entity",
        from = "Column::DeviceRegistryId",
        to = "super::device_registries::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::formulas::Entity",
        from = "Column::FormulaId",
        to = "super::formulas::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Formulas,
    #[sea_orm(
        belongs_to = "super::unit_conversions::Entity",
        from = "Column::UnitConversionId",
        to = "super::unit_conversions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UnitConversions,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::formulas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Formulas.def()
    }
}

impl Related<super::unit_conversions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitConversions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
