//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::FormulaKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "formulas")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub formula_type: FormulaKind,
    #[sea_orm(column_type = "Text")]
    pub expression: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_unit: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub fluid_config: Option<Json>,
    pub is_predefined: bool,
    #[sea_orm(unique)]
    pub global_id: Option<Uuid>,
    pub version: i32,
    pub category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub import_count: i32,
    pub compute_on_event: bool,
    pub cache_ttl: i32,
    pub last_computed_at: Option<DateTimeWithTimeZone>,
    pub org_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::formula_data_sources::Entity")]
    FormulaDataSources,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Organizations,
}

impl Related<super::formula_data_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormulaDataSources.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
