//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Hand-edited: device placements live in `device_placements` (D43, one
//! UNIQUE placement per device); `preview_kind`/`preview_id` = the
//! attached object shown first when the POI opens.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "map_pins")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub mode: String,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))", nullable)]
    pub latitude: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))", nullable)]
    pub longitude: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub x: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub y: Option<Decimal>,
    pub label: String,
    pub emoji: Option<String>,
    // Localisation libre dans le bâtiment (« Bât. A — Étage 2 — Salle 204 »).
    pub location_detail: Option<String>,
    // Aperçu épinglé : kind ∈ {media_asset, tour, dashboard} + id
    // (uuid string) de l'objet attaché montré en priorité à l'ouverture.
    pub preview_kind: Option<String>,
    pub preview_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
