//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "mcu_boards")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub soc: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::predefined_devices::Entity")]
    PredefinedDevices,
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
