//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mcu_boards")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub soc: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    /// Display name of the variant (« NodeMCU ESP8266 (v1.0) »).
    #[sea_orm(nullable)]
    pub pretty_name: Option<String>,
    /// PlatformIO board id of the variant (« nodemcuv2 »).
    #[sea_orm(nullable)]
    pub pio_board: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::predefined_devices::Entity")]
    PredefinedDevices,
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDevices.def()
    }
}
