//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// State of one captured audio segment (media-ingest.md D162). Bytes live
/// in the MediaStore under `storage_key` until transcribed, never here.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_segments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub stream_id: Uuid,
    pub seq: i64,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: DateTimeWithTimeZone,
    pub clock_source: String,
    pub storage_key: Option<String>,
    pub size_bytes: i64,
    pub state: String,
    pub asr_model_id: Option<Uuid>,
    pub asr_model_version: Option<i64>,
    pub asr_ms: Option<i64>,
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::media_streams::Entity",
        from = "Column::StreamId",
        to = "super::media_streams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaStreams,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::media_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaStreams.def()
    }
}
