//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uniq_media_versions_asset_number")]
    pub asset_id: Uuid,
    pub org_id: i64,
    #[sea_orm(unique_key = "uniq_media_versions_asset_number")]
    pub version_number: i64,
    pub filename: String,
    pub content_type: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    pub sha256: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_assets::Entity",
        from = "Column::AssetId",
        to = "super::media_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaAssets,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
