//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Declared media stream (media-ingest.md D159). The URL never carries a
/// credential; `secret_id` points at the vault (D113).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_streams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    pub slug: String,
    pub kind: String,
    pub url: String,
    pub secret_id: Option<Uuid>,
    pub enabled: bool,
    pub capture_on: String,
    pub asr_profile_id: Option<Uuid>,
    pub tracks: String,
    /// Video frames sampled per second when `tracks` has video (D175).
    pub fps: i32,
    pub segment_secs: i32,
    pub overlap_secs: i32,
    pub audio_retention: String,
    pub notify_channel_id: Option<Uuid>,
    pub timezone: String,
    pub tdm_checked_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tdm_note: Option<String>,
    pub capture_state: String,
    pub capture_error: Option<String>,
    pub capture_changed_at: Option<DateTimeWithTimeZone>,
    /// Tombstone (D159): a deleted stream keeps its row so its slug — the
    /// name of its O2 streams — is never given to another stream.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::asr_profiles::Entity",
        from = "Column::AsrProfileId",
        to = "super::asr_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AsrProfiles,
    #[sea_orm(
        belongs_to = "super::notify_channels::Entity",
        from = "Column::NotifyChannelId",
        to = "super::notify_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NotifyChannels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::asr_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AsrProfiles.def()
    }
}
