//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Check of an audio model on one carrier (media-ingest.md D167): a model
/// valid on the GPU worker can be too slow on the server.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ml_model_checks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub model_id: Uuid,
    pub carrier: String,
    pub check_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub check_error: Option<String>,
    pub load_ms: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rtf: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub wer: Option<f64>,
    pub checked_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::ml_models::Entity",
        from = "Column::ModelId",
        to = "super::ml_models::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MlModels,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::ml_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MlModels.def()
    }
}
