//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Vision model registry (camera-video.md D81) — ONNX bytes in the media
/// library (`asset_id`), inference spec here.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ml_models")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub task: String,
    pub family: String,
    pub asset_id: Uuid,
    pub asset_version: Option<i64>,
    pub input_width: i32,
    pub input_height: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub labels: Json,
    #[sea_orm(column_type = "Float")]
    pub score_threshold: f32,
    #[sea_orm(column_type = "Float")]
    pub nms_iou: f32,
    /// D100 check: `unchecked` | `valid` | `invalid`.
    pub check_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub check_error: Option<String>,
    pub infer_ms: Option<i64>,
    pub checked_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_assets::Entity",
        from = "Column::AssetId",
        to = "super::media_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaAssets,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
