//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (main levée sur la forme de `_entities/viz_widget_library.rs` —
//! régénérable par `cargo loco db entities` sans diff de fond).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notify_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    /// websocket | webhook — enum ouverte (extension ntfy/smtp/…).
    pub kind: String,
    pub name: String,
    /// Typed by kind; `secret` fields hold vault references
    /// `{"secret_id"}` (secrets.md lot S4), never a value.
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    pub enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
