//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (main levée sur la forme de `_entities/viz_widget_library.rs` —
//! régénérable par `cargo loco db entities` sans diff de fond).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notify_templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    /// Sujet minijinja optionnel (le corps seul suffit pour ntfy-like).
    #[sea_orm(column_type = "Text", nullable)]
    pub subject: Option<String>,
    /// Corps minijinja — contexte `{msg, meta, vars}` (D52).
    #[sea_orm(column_type = "Text")]
    pub body: String,
    /// Vars déclarées `[{name, example}]` — picker UI + fallback aperçu.
    #[sea_orm(column_type = "JsonBinary")]
    pub vars: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
