//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Org secrets vault (secrets.md D110): one encrypted value per row.
/// Never serialized to a client — the DTO is `pnex_core::OrgSecret`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "org_secrets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// `None` = platform secret (D116).
    pub org_id: Option<i64>,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub ciphertext: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub nonce: Vec<u8>,
    /// Keyring entry that encrypted the row (rotation, D112).
    pub key_id: String,
    pub created_by: Option<i64>,
    pub updated_by: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::secret_usages::Entity")]
    SecretUsages,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::secret_usages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecretUsages.def()
    }
}
