//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub subscription_tier_id: Option<i64>,
    pub data_retention_days: Option<i32>,
    /// Assistant conversation retention of the org (days, D145), at most
    /// the platform value; NULL follows the platform.
    pub ai_retention_days: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_records::Entity")]
    BuildRecords,
    #[sea_orm(has_many = "super::dashboards::Entity")]
    Dashboards,
    #[sea_orm(has_many = "super::device_registries::Entity")]
    DeviceRegistries,
    #[sea_orm(has_many = "super::flows::Entity")]
    Flows,
    #[sea_orm(has_many = "super::fluid_mixtures::Entity")]
    FluidMixtures,
    #[sea_orm(has_many = "super::formulas::Entity")]
    Formulas,
    #[sea_orm(has_many = "super::map_pins::Entity")]
    MapPins,
    #[sea_orm(has_many = "super::media_assets::Entity")]
    MediaAssets,
    #[sea_orm(has_many = "super::media_versions::Entity")]
    MediaVersions,
    #[sea_orm(has_one = "super::openobserve_orgs::Entity")]
    OpenobserveOrgs,
    #[sea_orm(has_many = "super::organization_members::Entity")]
    OrganizationMembers,
    #[sea_orm(has_many = "super::regulator_configs::Entity")]
    RegulatorConfigs,
    #[sea_orm(has_many = "super::stitch_jobs::Entity")]
    StitchJobs,
    #[sea_orm(
        belongs_to = "super::subscription_tiers::Entity",
        from = "Column::SubscriptionTierId",
        to = "super::subscription_tiers::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SubscriptionTiers,
    #[sea_orm(has_many = "super::unit_conversions::Entity")]
    UnitConversions,
}

impl Related<super::build_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildRecords.def()
    }
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboards.def()
    }
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::flows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flows.def()
    }
}

impl Related<super::fluid_mixtures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FluidMixtures.def()
    }
}

impl Related<super::formulas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Formulas.def()
    }
}

impl Related<super::map_pins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MapPins.def()
    }
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl Related<super::media_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaVersions.def()
    }
}

impl Related<super::openobserve_orgs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpenobserveOrgs.def()
    }
}

impl Related<super::organization_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrganizationMembers.def()
    }
}

impl Related<super::regulator_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegulatorConfigs.def()
    }
}

impl Related<super::stitch_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StitchJobs.def()
    }
}

impl Related<super::subscription_tiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionTiers.def()
    }
}

impl Related<super::unit_conversions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitConversions.def()
    }
}
