//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (doc comments à la main — régénérable par `cargo loco db entities`).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pnex_hosts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_pnex_hosts_org_host")]
    /// Org propriétaire (référentiel org-scoped, FK CASCADE).
    pub org_id: i64,
    #[sea_orm(unique_key = "uniq_pnex_hosts_org_host")]
    /// Bare host without scheme (`192.168.1.16`, `dev1.pnex.io`): devices
    /// always connect over wss (D154).
    pub host: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
