//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "predefined_device_capabilities")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub predefined_device_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_capability_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_capabilities::Entity",
        from = "Column::DeviceCapabilityId",
        to = "super::device_capabilities::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeviceCapabilities,
    #[sea_orm(
        belongs_to = "super::predefined_devices::Entity",
        from = "Column::PredefinedDeviceId",
        to = "super::predefined_devices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PredefinedDevices,
}

impl Related<super::device_capabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceCapabilities.def()
    }
}

impl Related<super::predefined_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDevices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
