//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "predefined_devices")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
    pub pretty_name: Option<String>,
    pub revision: String,
    pub device_doc_url: Option<String>,
    #[sea_orm(unique)]
    pub prestashop_product_id: Option<String>,
    pub prestashop_buy_url: Option<String>,
    pub byod_doc_url: Option<String>,
    pub image_source_url: Option<String>,
    pub stl_files_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub device_type_id: i64,
    pub board_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_registries::Entity")]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::device_types::Entity",
        from = "Column::DeviceTypeId",
        to = "super::device_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeviceTypes,
    #[sea_orm(
        belongs_to = "super::mcu_boards::Entity",
        from = "Column::BoardId",
        to = "super::mcu_boards::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    McuBoards,
    #[sea_orm(has_many = "super::predefined_device_capabilities::Entity")]
    PredefinedDeviceCapabilities,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::device_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceTypes.def()
    }
}

impl Related<super::mcu_boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::McuBoards.def()
    }
}

impl Related<super::predefined_device_capabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PredefinedDeviceCapabilities.def()
    }
}

impl Related<super::device_capabilities::Entity> for Entity {
    fn to() -> RelationDef {
        super::predefined_device_capabilities::Relation::DeviceCapabilities.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::predefined_device_capabilities::Relation::PredefinedDevices
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
