//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "regulator_configs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_regulator_config_slot")]
    pub node_id: String,
    pub kind: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    pub org_id: i64,
    #[sea_orm(unique_key = "uniq_regulator_config_slot")]
    pub device_registry_id: i64,
    #[sea_orm(unique_key = "uniq_regulator_config_slot")]
    pub flow_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_registries::Entity",
        from = "Column::DeviceRegistryId",
        to = "super::device_registries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DeviceRegistries,
    #[sea_orm(
        belongs_to = "super::flows::Entity",
        from = "Column::FlowId",
        to = "super::flows::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Flows,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::device_registries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceRegistries.def()
    }
}

impl Related<super::flows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flows.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
