//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "saved_views")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub site_diagram_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub zoom: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub pan_x: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub pan_y: Decimal,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::site_diagrams::Entity",
        from = "Column::SiteDiagramId",
        to = "super::site_diagrams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SiteDiagrams,
}

impl Related<super::site_diagrams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SiteDiagrams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
