//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "capability_mode")]
pub enum CapabilityMode {
    #[sea_orm(string_value = "input")]
    Input,
    #[sea_orm(string_value = "output")]
    Output,
    #[sea_orm(string_value = "input_output")]
    InputOutput,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "constant_kind")]
pub enum ConstantKind {
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "boolean")]
    Boolean,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "conversion_kind")]
pub enum ConversionKind {
    #[sea_orm(string_value = "linear")]
    Linear,
    #[sea_orm(string_value = "affine")]
    Affine,
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "data_source_kind")]
pub enum DataSourceKind {
    #[sea_orm(string_value = "device")]
    Device,
    #[sea_orm(string_value = "constant")]
    Constant,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "fluid_category")]
pub enum FluidCategory {
    #[sea_orm(string_value = "water")]
    Water,
    #[sea_orm(string_value = "refrigerant")]
    Refrigerant,
    #[sea_orm(string_value = "air")]
    Air,
    #[sea_orm(string_value = "hydrocarbon")]
    Hydrocarbon,
    #[sea_orm(string_value = "cryogenic")]
    Cryogenic,
    #[sea_orm(string_value = "mixture")]
    Mixture,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "fluid_group_type")]
pub enum FluidGroupType {
    #[sea_orm(string_value = "basic_thermo")]
    BasicThermo,
    #[sea_orm(string_value = "specific_heat")]
    SpecificHeat,
    #[sea_orm(string_value = "transport")]
    Transport,
    #[sea_orm(string_value = "psychrometric")]
    Psychrometric,
    #[sea_orm(string_value = "all_thermo")]
    AllThermo,
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "formula_kind")]
pub enum FormulaKind {
    #[sea_orm(string_value = "simple_math")]
    SimpleMath,
    #[sea_orm(string_value = "fluid_property")]
    FluidProperty,
    #[sea_orm(string_value = "power_calculation")]
    PowerCalculation,
    #[sea_orm(string_value = "rate_of_change")]
    RateOfChange,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "org_member_role")]
pub enum OrgMemberRole {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "viewer")]
    Viewer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "ui_theme")]
pub enum UiTheme {
    #[sea_orm(string_value = "light")]
    Light,
    #[sea_orm(string_value = "dark")]
    Dark,
    #[sea_orm(string_value = "auto")]
    Auto,
}
