//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "capability_mode")]
pub enum CapabilityMode {
    #[sea_orm(string_value = "input")]
    Input,
    #[sea_orm(string_value = "output")]
    Output,
    #[sea_orm(string_value = "input_output")]
    InputOutput,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "constant_kind")]
pub enum ConstantKind {
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "boolean")]
    Boolean,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "conversion_kind")]
pub enum ConversionKind {
    #[sea_orm(string_value = "linear")]
    Linear,
    #[sea_orm(string_value = "affine")]
    Affine,
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "data_source_kind")]
pub enum DataSourceKind {
    #[sea_orm(string_value = "device")]
    Device,
    #[sea_orm(string_value = "constant")]
    Constant,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "formula_kind")]
pub enum FormulaKind {
    #[sea_orm(string_value = "simple_math")]
    SimpleMath,
    #[sea_orm(string_value = "fluid_property")]
    FluidProperty,
    #[sea_orm(string_value = "power_calculation")]
    PowerCalculation,
    #[sea_orm(string_value = "rate_of_change")]
    RateOfChange,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "openobserve_org_status"
)]
pub enum OpenobserveOrgStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "provisioned")]
    Provisioned,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "org_member_role")]
pub enum OrgMemberRole {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "viewer")]
    Viewer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "ui_theme")]
pub enum UiTheme {
    #[sea_orm(string_value = "light")]
    Light,
    #[sea_orm(string_value = "dark")]
    Dark,
    #[sea_orm(string_value = "auto")]
    Auto,
}
