//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Which consumer field references which secret (secrets.md D114).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "secret_usages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub secret_id: Uuid,
    pub consumer_kind: String,
    pub consumer_id: String,
    pub field: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::org_secrets::Entity",
        from = "Column::SecretId",
        to = "super::org_secrets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OrgSecrets,
}

impl Related<super::org_secrets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgSecrets.def()
    }
}
