//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "site_diagrams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uniq_site_diagrams_site_svg")]
    pub site_id: Uuid,
    #[sea_orm(unique_key = "uniq_site_diagrams_site_svg")]
    pub svg_file_id: Uuid,
    pub display_name: String,
    pub display_order: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotations::Entity")]
    Annotations,
    #[sea_orm(has_many = "super::saved_views::Entity")]
    SavedViews,
    #[sea_orm(
        belongs_to = "super::sites::Entity",
        from = "Column::SiteId",
        to = "super::sites::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sites,
    #[sea_orm(
        belongs_to = "super::svg_files::Entity",
        from = "Column::SvgFileId",
        to = "super::svg_files::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SvgFiles,
}

impl Related<super::annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotations.def()
    }
}

impl Related<super::saved_views::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavedViews.def()
    }
}

impl Related<super::sites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sites.def()
    }
}

impl Related<super::svg_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SvgFiles.def()
    }
}
