//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stitch_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub asset_id: Uuid,
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub frames_total: i32,
    pub frames_received: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub poses_json: Json,
    #[sea_orm(column_type = "Float")]
    pub hfov_deg: f32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_assets::Entity",
        from = "Column::AssetId",
        to = "super::media_assets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaAssets,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::media_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaAssets.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
