//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Topic taxonomy of an org (media-ingest.md D168). Its topics live in the
/// append-only `taxonomy_versions`; `current_version` = 0 before the first.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "taxonomies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub current_version: i32,
    pub created_by: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::taxonomy_versions::Entity")]
    TaxonomyVersions,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::taxonomy_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxonomyVersions.def()
    }
}
