//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Append-only version of a taxonomy (D168, `flow_versions` school): its
/// topics (`pnex_core::taxonomy::Topic[]`), never rewritten.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "taxonomy_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub taxonomy_id: Uuid,
    pub version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub topics: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_by: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::taxonomies::Entity",
        from = "Column::TaxonomyId",
        to = "super::taxonomies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Taxonomies,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::taxonomies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taxonomies.def()
    }
}
