//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written on the generated shape — regenerable by
//! `cargo loco db entities` without a meaningful diff).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Named interval of a scope (media-ingest.md D169, D182): announced
/// (`planned_*`) and/or realigned (`actual_*`). At least one complete pair.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "time_ranges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    /// `stream` | `org`.
    pub scope_kind: String,
    pub scope_id: String,
    pub label: String,
    pub external_id: Option<String>,
    pub category: Option<String>,
    pub planned_start: Option<DateTimeWithTimeZone>,
    pub planned_end: Option<DateTimeWithTimeZone>,
    pub actual_start: Option<DateTimeWithTimeZone>,
    pub actual_end: Option<DateTimeWithTimeZone>,
    /// `epg` | `grid` | `detected` | `manual` | `import`.
    pub origin: String,
    #[sea_orm(column_type = "Float", nullable)]
    pub confidence: Option<f32>,
    pub source_url: Option<String>,
    /// Provenance, D184 format, built server side.
    pub source_ref: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub attrs: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
