//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Studio — versions append-only du document de parcours (école
//! `flow_versions`) : `doc` JSONB (`pnex_core::TourDoc`), unique
//! (tour_id, version_number).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tour_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uniq_tour_versions_tour_number")]
    pub tour_id: Uuid,
    #[sea_orm(unique_key = "uniq_tour_versions_tour_number")]
    pub version_number: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub doc: Json,
    pub author: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tours::Entity",
        from = "Column::TourId",
        to = "super::tours::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tours,
}

impl Related<super::tours::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tours.def()
    }
}
