//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//!
//! Studio: identity of a 3D tour. Circular FK `published_version_id`,
//! same pattern as `flows.deployed_version_id`.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tours")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub org_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub mode: String,
    #[sea_orm(unique)]
    pub share_token: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub published_version_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::tour_versions::Entity",
        from = "Column::PublishedVersionId",
        to = "super::tour_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    TourVersions,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::tour_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TourVersions.def()
    }
}
