//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ConversionKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "unit_conversions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[sea_orm(unique_key = "uniq_unit_conversions_predefined_units")]
    pub from_unit: String,
    #[sea_orm(unique_key = "uniq_unit_conversions_predefined_units")]
    pub to_unit: String,
    pub conversion_type: ConversionKind,
    #[sea_orm(column_type = "Double")]
    pub multiplier: f64,
    #[sea_orm(column_type = "Double")]
    pub offset: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub expression: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_predefined: bool,
    pub global_id: Option<Uuid>,
    pub version: i32,
    pub category: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Json>,
    pub import_count: i32,
    #[sea_orm(unique_key = "uniq_unit_conversions_org_units")]
    pub org_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::formula_data_sources::Entity")]
    FormulaDataSources,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Organizations,
}

impl Related<super::formula_data_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormulaDataSources.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
