//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//! (hand-written doc comments; the password lives in the secrets vault,
//! secrets.md S6).

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "wifi_credentials")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uniq_wifi_credentials_org_ssid")]
    /// Org propriétaire (référentiel org-scoped, FK CASCADE).
    pub org_id: i64,
    #[sea_orm(unique_key = "uniq_wifi_credentials_org_ssid")]
    /// Case-sensitive (byte-sensitive 802.11) — l'upsert (org, ssid) l'est aussi.
    pub ssid: String,
    /// Vault secret holding the password (secrets.md S6).
    pub secret_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
