[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -D HOST=\"${sysenv.HOST}\"
    -D TOKEN=\"${sysenv.TOKEN}\"
    -D DEVICE_ID=\"${sysenv.DEVICE_ID}\"
    -D ENCRYPTION_KEY=\"${sysenv.ENCRYPTION_KEY}\"
    -D WS_SSL=\"${sysenv.WS_SSL}\"
lib_extra_dirs = ../common_libs
lib_deps =
    SPI
    Wire
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.4
    densaugeo/base64@^1.4.0
    gilmaimon/ArduinoWebsockets@^0.5.4
    olikraus/U8g2@^2.36.12
