#!/usr/bin/env bash
# TLS edge (D70) — `task edge:up`: brings nginx + the local PKI (or
# certbot) up in front of Rauthy and the backend, on a single origin
# https://$PNEX_DOMAIN. Idempotent, safe to replay.
#
#   PNEX_DOMAIN      default: `<hostname>.<router search domain>` when the
#                    router's DNS knows it, else `<hostname>.local` (mDNS) —
#                    no /etc/hosts edits anywhere
#   PNEX_EDGE_MODE   local (default, local CA) | cloud (Let's Encrypt)
#   PNEX_EXTRA_SANS  optional extra SANs for the local leaf, e.g.
#                    "IP:192.168.1.185" (devices connecting by IP)
#   ACME_EMAIL       required in cloud mode; ACME_STAGING=1 while testing
#   PNEX_EDGE_BACKEND  host (default: backend run by `task dev:backend`) |
#                    container (pnex-server image, compose.app.yaml — D71)
#
# Writes deploy/edge/edge.env (read by `task dev:backend`) so the backend
# advertises the https issuer. `task edge:down` reverts everything.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# Default name: the router's DNS entry `<hostname>.<search domain>` when it
# resolves (e.g. `.home` on Livebox — plain DNS, works in every browser and
# on phones), else mDNS `<hostname>.local` (browsers with DoH, and some
# avahi/systemd-resolved setups, fail to resolve it).
default_domain() {
    local host search
    host=$(hostname | tr '[:upper:]' '[:lower:]')
    search=$(awk '/^(search|domain) /{print $2; exit}' /etc/resolv.conf 2>/dev/null)
    if [[ -n $search && $search != local ]] && getent hosts "$host.$search" >/dev/null; then
        echo "$host.$search"
    else
        echo "$host.local"
    fi
}
# The name is sticky: once chosen it stays (firmware + OIDC client depend
# on it) — router DNS entries come and go with DHCP leases, so auto-detect
# only runs on the very first edge:up. Override with PNEX_DOMAIN=….
previous_domain() {
    [[ -f deploy/edge/edge.env ]] && sed -n 's/^PNEX_DOMAIN=//p' deploy/edge/edge.env
}
DOMAIN="${PNEX_DOMAIN:-$(previous_domain)}"
DOMAIN="${DOMAIN:-$(default_domain)}"
MODE="${PNEX_EDGE_MODE:-local}"
case $MODE in
    local|cloud) ;;
    *) echo "ERROR: PNEX_EDGE_MODE must be local or cloud (got '$MODE')"; exit 1 ;;
esac
export PNEX_DOMAIN="$DOMAIN" PNEX_EDGE_MODE="$MODE"
# An IP origin (no reliable LAN DNS) is fine for TLS and OIDC, but WebAuthn
# rejects IP rp ids → passkeys scoped to localhost.
if [[ $DOMAIN =~ ^[0-9]+(\.[0-9]+){3}$ ]]; then
    export PNEX_RP_ID=localhost
else
    export PNEX_RP_ID="$DOMAIN"
fi
export PNEX_EXTRA_SANS="${PNEX_EXTRA_SANS:-}"
# LAN IPv4s of this machine (devices registered by IP — the LAN scan
# returns bare IPs): both `IP:` (browsers) and `DNS:` (mbedTLS 2.x on
# ESP32 only matches dNSName entries). Sorted → no needless re-issue.
if [[ $MODE == local ]]; then
    for ip in $(ip -4 -o addr show scope global 2>/dev/null \
        | awk '$2 !~ /^(docker|br-|veth|virbr|lxcbr)/ {split($4,a,"/"); print a[1]}' | sort -u); do
        PNEX_EXTRA_SANS="${PNEX_EXTRA_SANS:+$PNEX_EXTRA_SANS,}IP:$ip,DNS:$ip"
    done
fi
# mDNS alias `<hostname>.local`: covered by the leaf and 301-redirected by
# nginx to the canonical name (a single origin keeps the OIDC client and
# cookies consistent).
ALIAS="$(hostname | tr '[:upper:]' '[:lower:]').local"
if [[ $MODE == local && $ALIAS != "$DOMAIN" ]]; then
    PNEX_EXTRA_SANS="DNS:$ALIAS${PNEX_EXTRA_SANS:+,$PNEX_EXTRA_SANS}"
    export PNEX_DOMAIN_ALIAS="$ALIAS"
else
    export PNEX_DOMAIN_ALIAS=""
fi
# Edge <-> backend shared secret (X-Pnex-Edge): the backend trusts the edge's
# headers (X-Forwarded-Proto, X-Client-Cert) only with it. Sticky, like the
# domain: generated once, kept in edge.env.
previous_secret() {
    [[ -f deploy/edge/edge.env ]] && sed -n 's/^PNEX_EDGE_SECRET=//p' deploy/edge/edge.env
}
EDGE_SECRET="${PNEX_EDGE_SECRET:-$(previous_secret)}"
EDGE_SECRET="${EDGE_SECRET:-$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 40)}"
# Device endpoint (D158): its own TLS listener asking for the device client
# certificate, so browsers on 443 are never asked for one.
DEVICE_PORT="${PNEX_DEVICE_PORT:-4443}"
export PNEX_EDGE_SECRET="$EDGE_SECRET" PNEX_DEVICE_PORT="$DEVICE_PORT"
BACKEND="${PNEX_EDGE_BACKEND:-host}"
case $BACKEND in
    host|container) ;;
    *) echo "ERROR: PNEX_EDGE_BACKEND must be host or container (got '$BACKEND')"; exit 1 ;;
esac
[[ $MODE == cloud && -z ${ACME_EMAIL:-} ]] && { echo "ERROR: ACME_EMAIL is required in cloud mode"; exit 1; }
echo "Edge: https://$DOMAIN (mode $MODE, backend $BACKEND)"

# ── 1) Env file for the host-side backend ───────────────────────────────
cat > deploy/edge/edge.env <<EOF
# Generated by deploy/edge/apply-edge.sh — removed by task edge:down.
PNEX_DOMAIN=$DOMAIN
PNEX_EDGE_MODE=$MODE
PNEX_EXTRA_SANS=$PNEX_EXTRA_SANS
RAUTHY_ISSUER_URL=https://$DOMAIN
PNEX_CA_CERT_FILE=$ROOT/deploy/edge/pki-data/device-ca.pem
PNEX_EDGE_SECRET=$EDGE_SECRET
PNEX_DEVICE_PORT=$DEVICE_PORT
EOF
chmod 600 deploy/edge/edge.env
echo "  ✓ deploy/edge/edge.env"

# ── 2) Stack up (rauthy recreated with the proxy-mode overrides) ────────
mkdir -p deploy/edge/pki-data
export RAUTHY_ISSUER_URL="https://$DOMAIN"
COMPOSE=(docker compose -f compose.yaml -f compose.edge.yaml)
SERVICES=(rauthy edge-pki edge-nginx)
[[ $MODE == cloud ]] && { COMPOSE+=(--profile cloud); SERVICES+=(edge-certbot); }
if [[ $BACKEND == container ]]; then
    COMPOSE+=(-f compose.app.yaml)
    SERVICES+=(pnex-server pnex-builder)
    export PNEX_BACKEND_UPSTREAM="pnex-server:5150"
else
    # Host-run backend: reach it through the compose network gateway (an
    # IP literal, so nginx needs no DNS for it). rauthy first creates the
    # network (placeholder: the overlay refuses to parse without it).
    PNEX_BACKEND_UPSTREAM=pending "${COMPOSE[@]}" up -d rauthy >/dev/null
    NET=$(docker inspect pnex-rauthy -f '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}')
    GW=$(docker network inspect "$NET" -f '{{(index .IPAM.Config 0).Gateway}}')
    export PNEX_BACKEND_UPSTREAM="$GW:5150"
fi
echo "  ✓ backend upstream: $PNEX_BACKEND_UPSTREAM"
"${COMPOSE[@]}" up -d "${SERVICES[@]}"
docker logs pnex-edge-pki 2>&1 | grep '^\[pki\]' | sed 's/^/  /' || true

# ── 3) Wait for the public issuer through nginx ─────────────────────────
CURL_TLS=(--resolve "$DOMAIN:443:127.0.0.1")
if [[ $MODE == local ]]; then
    CURL_TLS+=(--cacert deploy/edge/pki-data/ca.pem)
else
    CURL_TLS+=(-k)  # the placeholder may still be served until certbot is done
fi
DISCOVERY="https://$DOMAIN/auth/v1/.well-known/openid-configuration"
ISSUER=""
for _ in $(seq 1 30); do
    ISSUER=$(curl -sf "${CURL_TLS[@]}" "$DISCOVERY" 2>/dev/null \
        | python3 -c "import json,sys; print(json.load(sys.stdin)['issuer'])" 2>/dev/null) && break
    sleep 1
done
[[ -n $ISSUER ]] || { echo "ERROR: $DISCOVERY unreachable (docker logs pnex-edge-nginx / pnex-rauthy)"; exit 1; }
echo "  ✓ discovery issuer: $ISSUER"
[[ $ISSUER == "https://$DOMAIN/auth/v1"* ]] || echo "WARNING: unexpected issuer (expected https://$DOMAIN/auth/v1/)"

# ── 4) Extend the `pnex` OIDC client live (bootstrap JSON is first-init only)
KEY="${RAUTHY_API_KEY:-pnex-branding\$c1cb445debf753d916623fc2e0d996cef9a73f3b4664a9d3d29d16a5e5113e5c}"
BASE="http://127.0.0.1:8080"
AUTH="Authorization: API-Key $KEY"
JSON=$(curl -sf -H "$AUTH" "$BASE/auth/v1/clients/pnex") || {
    echo "ERROR: GET client pnex failed (API key valid?)"; exit 1; }
NEW_JSON=$(DOMAIN="$DOMAIN" python3 - "$JSON" <<'PY'
import json, os, sys

client = json.loads(sys.argv[1])
origin = f"https://{os.environ['DOMAIN']}"
wanted = {
    "redirect_uris": [f"{origin}/auth/callback", f"{origin}/api/v1/oauth2/native"],
    "post_logout_redirect_uris": [f"{origin}/"],
    "allowed_origins": [origin],  # Rauthy rejects a trailing slash here
}
added = 0
for field, values in wanted.items():
    current = client.get(field) or []
    for v in values:
        if v not in current:
            current.append(v)
            added += 1
    client[field] = current
print(json.dumps(client))
print(f"  ✓ client pnex: +{added} URIs/origins" if added else "  • client pnex already up to date", file=sys.stderr)
PY
)
code=$(curl -s -o /dev/null -w '%{http_code}' -X PUT -H "$AUTH" \
    -H 'Content-Type: application/json' -d "$NEW_JSON" "$BASE/auth/v1/clients/pnex")
[[ $code == 2* ]] || { echo "ERROR: PUT client pnex → HTTP $code"; exit 1; }

echo ""
echo "Edge up. Next steps:"
if [[ $BACKEND == host ]]; then
    echo "  • (re)start the backend with 'task dev:backend' — it reads deploy/edge/edge.env"
else
    echo "  • pnex-server + pnex-builder run in containers (task app:down to stop them)"
fi
[[ $MODE == local ]] && echo "  • trust the local CA once per machine: 'task edge:trust' (root CA: deploy/edge/pki-data/ca.pem)"
echo "  • open https://$DOMAIN"
