"""Patche le AndroidManifest.xml généré par dx (régénéré à chaque build,
avec un formatage qui VARIE d'une génération à l'autre — donc patch par
regex tolérantes aux espaces, jamais par blocs littéraux).

dx ne permet pas d'injecter du XML au niveau de l'activité (le raw manifest
Dioxus.toml n'alimente que le niveau `<manifest>`) : ce script, lancé APRÈS
`dx build` et AVANT le ré-assemblage gradle (Taskfile `build:frontend:android`),
ajoute à `dev.dioxus.main.MainActivity` :

- `android:launchMode="singleTask"` — un deep link ne crée pas une seconde
  instance (onNewIntent no-op, l'UI existante reste en l'état) ;
- un intent-filter VIEW/BROWSABLE sur le schéma `pnex` — les navigateurs
  (Chromium) refusent de déclencher des cibles sans catégorie BROWSABLE :
  c'est ce qui rend le retour automatique à l'app possible depuis la page
  pont du login natif (`pnex://return`, cf. contrôleur `oauth2.rs`).

Et pour la capture photo média (D21, `src/capture.rs`) :

- un `<provider>` `androidx.core.content.FileProvider` (autorité
  `{package}.fileprovider` — le package est lu dans le manifest même, jamais
  hardcodé) ;
- le fichier `app/src/main/res/xml/file_paths.xml` (dossier `camera/` du
  cache, (re)créé à chaque build : le projet gradle est régénéré par dx) ;
- la dépendance gradle `androidx.core:core` si absente (FileProvider).

NOTE : la permission `<uses-permission android:name="android.permission.CAMERA"/>`
est POSÉE depuis Take 360 (preview getUserMedia dans la webview — wry
demande la permission runtime tout seul via son RustWebChromeClient).
Conséquence (Android ≥ 7) : l'intent ACTION_IMAGE_CAPTURE lève
SecurityException si la permission est déclarée mais non accordée — le
flux photo (`src/capture.rs`) gagne donc un pre-check
`camera_granted()`/`request_camera()` + toast avant tout startActivity.

And for TLS everywhere (D70): `res/xml/network_security_config.xml`
(generated by dx, referenced by the manifest) gains a `<base-config>` that
trusts user-installed CAs next to system ones — since API 24 the WebView
and the system components ignore user CAs unless the app opts in. The
Rust HTTP client does not go through this file (it pins the edge CA itself,
cf. `src/api/tls.rs`).

Idempotent : relancer sans risque, ne duplique rien.
"""

import re
import shutil
import sys
from pathlib import Path

MARKER = 'android:scheme="pnex"'  # présent = patch déjà appliqué

FILTER = (
    '<intent-filter><action android:name="android.intent.action.VIEW" />'
    '<category android:name="android.intent.category.DEFAULT" />'
    '<category android:name="android.intent.category.BROWSABLE" />'
    '<data android:scheme="pnex" /></intent-filter>'
)


def main(path: str) -> None:
    patch_single_task(path)
    patch_camera_permission(path)
    patch_media_provider(path)
    patch_network_security(path)
    patch_no_backup(path)
    patch_launcher_icon(path)
    patch_app_label(path)


def patch_single_task(path: str) -> None:
    with open(path, encoding="utf-8") as fh:
        xml = fh.read()

    if MARKER in xml:
        print("manifest déjà patché")
        return

    # 1) launchMode : repérer le tag <activity …> (multi-lignes) portant le
    #    nom de l'activité, insérer l'attribut juste après "<activity".
    tag_re = re.compile(r"<activity\b[^>]*>", re.S)
    target = None
    for match in tag_re.finditer(xml):
        if 'android:name="dev.dioxus.main.MainActivity"' in match.group(0):
            target = match
            break
    if target is None:
        sys.exit("activité MainActivity introuvable — template dx changé ?")
    xml = xml[: target.start()] + '<activity android:launchMode="singleTask" ' + xml[
        target.start() + len("<activity") :
    ]

    # 2) intent-filter deep link : insérer juste après le filtre portant
    #    ACTION_MAIN (le launcher), quel que soit son indentation.
    main_re = re.compile(r"<intent-filter\b.*?</intent-filter>", re.S)
    insert_at = None
    for match in main_re.finditer(xml):
        if "android.intent.action.MAIN" in match.group(0):
            insert_at = match.end()
            break
    if insert_at is None:
        sys.exit("filtre MAIN/LAUNCHER introuvable — template dx changé ?")
    xml = xml[:insert_at] + FILTER + xml[insert_at:]

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(xml)
    print("manifest patché (singleTask + deep link pnex)")


def patch_camera_permission(path: str) -> None:
    """Take 360 : permission CAMERA au manifest.

    La demande runtime est gérée par wry (RustWebChromeClient :
    onPermissionRequest VIDEO_CAPTURE → launcher Capacitor) et côté
    capture.rs pour l'intent photo. Idempotent.
    """
    with open(path, encoding="utf-8") as fh:
        xml = fh.read()

    if "android.permission.CAMERA" in xml:
        print("permission CAMERA déjà présente")
        return
    app_open = xml.find("<application")
    if app_open == -1:
        sys.exit("<application> introuvable — template dx changé ?")
    uses = '<uses-permission android:name="android.permission.CAMERA" />'
    xml = xml[:app_open] + uses + xml[app_open:]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(xml)
    print("permission CAMERA ajoutée")


def patch_media_provider(manifest_path: str) -> None:
    """Capture photo (D21) : FileProvider + file_paths.xml + dep gradle.

    Le manifest contient l'attribut `package=` (ou le namespace gradle le
    déclare) : l'autorité FileProvider est `{package}.fileprovider` — le
    package est lu dans le XML, jamais hardcodé (capture.rs reconstruit la
    même autorité au runtime via getPackageName()).
    """
    manifest = Path(manifest_path)
    # …/release/android/app/app/src/main/AndroidManifest.xml → module gradle
    # = main→src→app (3 niveaux : projet dx « app » contenant le module « app »).
    app_dir = manifest.parent.parent.parent

    with open(manifest_path, encoding="utf-8") as fh:
        xml = fh.read()

    # 1) package : attribut manifest (si présent) sinon namespace gradle.
    package = None
    pkg_match = re.search(r'package="([^"]+)"', xml)
    if pkg_match:
        package = pkg_match.group(1)
    else:
        for gradle_name in ("build.gradle.kts", "build.gradle"):
            gradle = app_dir / gradle_name
            if gradle.exists():
                ns = re.search(
                    r'namespace\s*=?\s*"([^"]+)"', gradle.read_text(encoding="utf-8")
                )
                if ns:
                    package = ns.group(1)
                    break
    if not package:
        sys.exit("package introuvable (manifest/gradle) — template dx changé ?")

    # 2) <provider> FileProvider avant </application>.
    if "androidx.core.content.FileProvider" not in xml:
        provider = (
            f'<provider android:name="androidx.core.content.FileProvider" '
            f'android:authorities="{package}.fileprovider" '
            f'android:exported="false" android:grantUriPermissions="true">'
            f'<meta-data android:name="android.support.FILE_PROVIDER_PATHS" '
            f'android:resource="@xml/file_paths" /></provider>'
        )
        app_close = xml.rfind("</application>")
        if app_close == -1:
            sys.exit("</application> introuvable — template dx changé ?")
        xml = xml[:app_close] + provider + xml[app_close:]
        with open(manifest_path, "w", encoding="utf-8") as fh:
            fh.write(xml)
        print(f"FileProvider ajouté (autorité {package}.fileprovider)")
    else:
        print("FileProvider déjà présent")

    # 3) res/xml/file_paths.xml — (re)créé à chaque build (dossier régénéré).
    res_xml = app_dir / "src" / "main" / "res" / "xml"
    res_xml.mkdir(parents=True, exist_ok=True)
    paths_file = res_xml / "file_paths.xml"
    if not paths_file.exists():
        paths_file.write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            "<paths>\n"
            '    <cache-path name="media_cache" path="camera/" />\n'
            "</paths>\n",
            encoding="utf-8",
        )
        print("file_paths.xml créé")

    # 4) dep gradle androidx.core si absente (FileProvider vit dans core).
    for gradle_name in ("build.gradle.kts", "build.gradle"):
        gradle = app_dir / gradle_name
        if gradle.exists():
            content = gradle.read_text(encoding="utf-8")
            if "androidx.core" in content:
                print(f"{gradle_name} : androidx.core déjà présent")
                return
            dep = (
                '    implementation("androidx.core:core:1.13.1")\n'
                if gradle_name.endswith(".kts")
                else '    implementation "androidx.core:core:1.13.1"\n'
            )
            if "dependencies {" in content:
                content = content.replace(
                    "dependencies {", "dependencies {\n" + dep, 1
                )
            else:
                content += "\ndependencies {\n" + dep + "}\n"
            gradle.write_text(content, encoding="utf-8")
            print(f"{gradle_name} : androidx.core ajouté")
            return
    sys.exit("build.gradle introuvable — template dx changé ?")


USER_CA_MARKER = '<certificates src="user"'

BASE_CONFIG = (
    "<base-config>"
    '<trust-anchors><certificates src="system" /><certificates src="user" /></trust-anchors>'
    "</base-config>"
)


def patch_network_security(manifest_path: str) -> None:
    """D70: trust user-installed CAs (local edge root) in the WebView.

    dx writes `network_security_config.xml` (cleartext for 127.0.0.1) and
    references it from `<application>`; the dx rules are kept, a
    `<base-config>` is added. If dx ever stops generating it, the file and
    the manifest attribute are created. Idempotent.
    """
    manifest = Path(manifest_path)
    app_dir = manifest.parent.parent.parent
    res_xml = app_dir / "src" / "main" / "res" / "xml"
    res_xml.mkdir(parents=True, exist_ok=True)
    nsc = res_xml / "network_security_config.xml"

    if nsc.exists():
        content = nsc.read_text(encoding="utf-8")
    else:
        content = (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            "<network-security-config>\n</network-security-config>\n"
        )
    if USER_CA_MARKER in content:
        print("network_security_config: user CAs already trusted")
    else:
        if "<base-config" in content:
            sys.exit("network_security_config: unexpected dx base-config — dx template changed?")
        open_tag = re.search(r"<network-security-config[^>]*>", content)
        if open_tag is None:
            sys.exit("network_security_config unreadable — dx template changed?")
        content = content[: open_tag.end()] + BASE_CONFIG + content[open_tag.end() :]
        nsc.write_text(content, encoding="utf-8")
        print("network_security_config: user CAs trusted")

    xml = manifest.read_text(encoding="utf-8")
    if "android:networkSecurityConfig" not in xml:
        app_tag = re.search(r"<application\b", xml)
        if app_tag is None:
            sys.exit("<application> not found — dx template changed?")
        xml = (
            xml[: app_tag.end()]
            + ' android:networkSecurityConfig="@xml/network_security_config"'
            + xml[app_tag.end() :]
        )
        manifest.write_text(xml, encoding="utf-8")
        print("networkSecurityConfig referenced in the manifest")


# Every storage domain excluded from cloud backup and device-to-device
# transfer (Android 12+ reads these rules, older releases `allowBackup`).
DATA_EXTRACTION_RULES = """<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </device-transfer>
</data-extraction-rules>
"""


def patch_no_backup(manifest_path: str) -> None:
    """No Android backup of the app data (security.md R16).

    `files/pnex-storage.json` holds the refresh token: the default
    `allowBackup=true` put it in Google auto-backup and device transfers
    (anyone restoring the backup gets a long-lived session). Idempotent.
    """
    manifest = Path(manifest_path)
    res_xml = manifest.parent.parent.parent / "src" / "main" / "res" / "xml"
    res_xml.mkdir(parents=True, exist_ok=True)
    (res_xml / "data_extraction_rules.xml").write_text(DATA_EXTRACTION_RULES, encoding="utf-8")

    xml = manifest.read_text(encoding="utf-8")
    if "android:allowBackup" in xml:
        print("allowBackup already set")
        return
    app_tag = re.search(r"<application\b", xml)
    if app_tag is None:
        sys.exit("<application> not found — dx template changed?")
    xml = (
        xml[: app_tag.end()]
        + ' android:allowBackup="false"'
        + ' android:fullBackupContent="false"'
        + ' android:dataExtractionRules="@xml/data_extraction_rules"'
        + xml[app_tag.end() :]
    )
    manifest.write_text(xml, encoding="utf-8")
    print("app data excluded from Android backup")


# PNeX "X" mark (assets/logo-mark.png redrawn as vectors) on the 108-unit
# adaptive-icon viewport; everything stays inside the 66-unit safe zone.
ICON_BACKGROUND = """<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#FFFFFF" android:pathData="M0,0h108v108h-108z" />
</vector>
"""

ICON_FOREGROUND = """<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:strokeColor="#E4462A" android:strokeWidth="6.5"
        android:strokeLineCap="round" android:pathData="M33,33L75,75M75,33L33,75" />
    <path android:fillColor="#FFFFFF"
        android:pathData="M54,47.6a6.4,6.4 0,1 1,0 12.8a6.4,6.4 0,1 1,0 -12.8z" />
    <path android:fillColor="#59C7D4"
        android:pathData="M54,49.4a4.6,4.6 0,1 1,0 9.2a4.6,4.6 0,1 1,0 -9.2z" />
</vector>
"""


def patch_launcher_icon(manifest_path: str) -> None:
    """Launcher icon: PNeX mark instead of dx's Android Studio template robot.

    dx regenerates `res/` on every build with the stock template icon
    (green #3DDC84 background) and offers no Dioxus.toml knob for it on
    Android. API 26+ uses the adaptive vectors below; API 24-25 falls back to
    the PNGs versioned in `android-res/` (rendered from the same geometry).
    The template ships them as `.webp`: removed, otherwise gradle fails on a
    duplicate `ic_launcher` resource. Idempotent.
    """
    res = Path(manifest_path).parent / "res"
    (res / "drawable").mkdir(parents=True, exist_ok=True)
    (res / "drawable-v24").mkdir(parents=True, exist_ok=True)
    (res / "drawable" / "ic_launcher_background.xml").write_text(
        ICON_BACKGROUND, encoding="utf-8"
    )
    (res / "drawable-v24" / "ic_launcher_foreground.xml").write_text(
        ICON_FOREGROUND, encoding="utf-8"
    )
    legacy = Path(__file__).parent / "android-res"
    for src in sorted(legacy.glob("mipmap-*/ic_launcher.png")):
        dest_dir = res / src.parent.name
        dest_dir.mkdir(parents=True, exist_ok=True)
        for stale in dest_dir.glob("ic_launcher.*"):
            stale.unlink()
        shutil.copyfile(src, dest_dir / "ic_launcher.png")
    print("launcher icon replaced (PNeX mark)")


APP_LABEL = "PNeX"


def patch_app_label(manifest_path: str) -> None:
    """Launcher label: "PNeX" instead of dx's crate-derived "PnexFrontend".

    dx writes `app_name` into `res/values/strings.xml` from the crate name,
    with no Dioxus.toml override. Idempotent.
    """
    strings = Path(manifest_path).parent / "res" / "values" / "strings.xml"
    xml = strings.read_text(encoding="utf-8")
    patched, count = re.subn(
        r'(<string name="app_name">)[^<]*(</string>)', rf"\g<1>{APP_LABEL}\g<2>", xml
    )
    if count == 0:
        sys.exit("app_name not found in strings.xml — dx template changed?")
    strings.write_text(patched, encoding="utf-8")
    print(f"app label set to {APP_LABEL}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: patch-android-manifest.py <AndroidManifest.xml>")
    main(sys.argv[1])
