"""Turns the gradle project generated by dx into a signed release build
(P1.2, SEC-10): the APK distributed so far was the `debug` build type,
signed with the dx debug key and `debuggable` (the session can be read over
USB with `run-as`).

Run AFTER `dx build` (which regenerates the gradle project on every build)
and BEFORE `./gradlew assembleRelease` (Taskfile `build:frontend:android:release`).
Patches `app/build.gradle.kts`:

- a `release` signing config read from the environment at gradle time, so
  that no secret is ever written to disk by this script:
  PNEX_ANDROID_KEYSTORE (path), PNEX_ANDROID_KEYSTORE_PASSWORD,
  PNEX_ANDROID_KEY_ALIAS, PNEX_ANDROID_KEY_PASSWORD;
- `isMinifyEnabled = false` on the release type: R8 would strip or rename
  the Java classes reached only through JNI by name (wry, ndk-context,
  webbrowser, our own JNI calls in src/), which compiles fine and crashes
  at runtime;
- `versionCode` / `versionName` from PNEX_ANDROID_VERSION_CODE /
  PNEX_ANDROID_VERSION_NAME when set (dx always writes 1 / the crate
  version, and an upgrade needs a strictly greater code). Without an
  explicit code, it is derived from the version name (`version_code`).

Idempotent: running it twice changes nothing.
"""

import os
import re
import sys
from pathlib import Path

MARKER = "// pnex: release signing"

SIGNING = f"""    {MARKER}
    signingConfigs {{
        create("release") {{
            storeFile = file(System.getenv("PNEX_ANDROID_KEYSTORE") ?: error("PNEX_ANDROID_KEYSTORE is not set"))
            storePassword = System.getenv("PNEX_ANDROID_KEYSTORE_PASSWORD")
            keyAlias = System.getenv("PNEX_ANDROID_KEY_ALIAS")
            keyPassword = System.getenv("PNEX_ANDROID_KEY_PASSWORD")
        }}
    }}
"""


def version_code(name: str) -> int:
    """Monotonic code from a semver name, pre-releases ordered
    alpha < beta < rc < final: 0.1.0-alpha.3 → 100003, 0.1.0-beta.7 →
    100207, 0.1.0-rc.2 → 100502, 0.1.0 → 100999, 1.2.3 → 10203999."""
    m = re.fullmatch(r"v?(\d+)\.(\d+)\.(\d+)(?:-(alpha|beta|rc)\.(\d+))?", name)
    if not m:
        sys.exit(f"patch-android-release: cannot derive a versionCode from {name!r}")
    major, minor, patch_, stage, n = m.groups()
    pre = 999
    if stage is not None:
        if int(n) >= 200:
            sys.exit(f"patch-android-release: pre-release number too large in {name!r}")
        pre = {"alpha": 0, "beta": 200, "rc": 500}[stage] + int(n)
    return int(major) * 10_000_000 + int(minor) * 100_000 + int(patch_) * 1_000 + pre


def patch(text: str) -> str:
    if MARKER not in text:
        text, n = re.subn(r"(android\s*\{\s*\n)", lambda m: m.group(1) + SIGNING, text, count=1)
        if n != 1:
            sys.exit("patch-android-release: `android {` block not found")

    release = re.search(r'getByName\("release"\)\s*\{', text)
    if not release:
        sys.exit("patch-android-release: release build type not found")
    body_start = release.end()
    if "signingConfig = signingConfigs.getByName(\"release\")" not in text:
        text = (
            text[:body_start]
            + '\n            signingConfig = signingConfigs.getByName("release")'
            + text[body_start:]
        )
    text = re.sub(
        r'(getByName\("release"\)\s*\{[^}]*?)isMinifyEnabled\s*=\s*true',
        r"\1isMinifyEnabled = false",
        text,
        count=1,
        flags=re.S,
    )

    name = os.environ.get("PNEX_ANDROID_VERSION_NAME")
    code = os.environ.get("PNEX_ANDROID_VERSION_CODE") or (str(version_code(name)) if name else None)
    if code:
        if not code.isdigit():
            sys.exit(f"patch-android-release: PNEX_ANDROID_VERSION_CODE={code!r} is not a number")
        text = re.sub(r"versionCode\s*=\s*\d+", f"versionCode = {code}", text, count=1)
    if name:
        if not re.fullmatch(r"[0-9A-Za-z.+-]+", name):
            sys.exit(f"patch-android-release: PNEX_ANDROID_VERSION_NAME={name!r} is not a version")
        text = re.sub(r'versionName\s*=\s*"[^"]*"', f'versionName = "{name}"', text, count=1)
    return text


def main(path: str) -> None:
    gradle = Path(path)
    before = gradle.read_text()
    after = patch(before)
    if after != before:
        gradle.write_text(after)
    print(f"patch-android-release: {gradle} ok")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: patch-android-release.py <app/build.gradle.kts>")
    main(sys.argv[1])
